### ISSUE TITLE
Standalone browser version

### ISSUE THREAD

**Issue by Pickachu** [Agamnentzar/ag-psd#1]
I'm currently trying to use the browser version for this library.

Doing the following:

`npm install ag-psd`
`<script src="ag-psd/dist/browser.js" />` or `<script src="ag-psd/dist/index.js" />`

Gives me the error: **Uncaught ReferenceError: exports is not defined**
on line: `Object.defineProperty(exports, "__esModule", { value: true });`

It seems something related to typescript building, do i have to include some special lib in order to this build work properly?

Also, would it not be nice to provide a standalone version?

**Comment by Agamnentzar** [comment]
It's commonjs style library, you have to import is using System.js, browserify, webpack, etc

**Comment by Agamnentzar** [comment]
Just pushed update with `bundle.js` so you can use it without any module manager

```html
<script src="node_modules/ag-psd/dist/bundle.js"></script>
<script>
  var readPsd = agPsd.readPsd;
  // rest of the code as in other examples
</script>
```

**Comment by Pickachu** [comment]
Awesome! Thanks Agamnentzar, i just spend an hour recompiling from commonjs to ES5 pure and using on Meteor 1.5. It is not easy to use System.js, wepack, etc on our implementation, meteor has it's own bundling system it is full ES5 import compatible.

But i will be switching to your bundled mantained version here, thanks.

In the occasion i'm also writing some image resource block parsers that are missing. Namely the Resolution Information and the Grid and Guides Information blocks. But in pure js, not typescript. 

If get the time i'll be opening a PR for them. But if you want i can send you the pure JS implementation and you can convert to TS and update the repo.

thanks for the fast response!

**Comment by Agamnentzar** [comment]
Sure I'll be up for adding more handlers, would be also nice if you could provide some example PSDs with those resources to add to the tests

**Comment by Pickachu** [comment]
Nice, i'm creating my PSD's and my own simple tests here to. So will be glad to send the tests and files along.
