### ISSUE TITLE
Compatibility with Sharp as an input?

### ISSUE THREAD

**Issue by richardtallent** [Agamnentzar/ag-psd#100]
I'm already using node [sharp](https://github.com/lovell/sharp) to pre-process the images I want to stack into a PSD.

Do you happen to know if the bitmap streams (8bpp of course) from that library (which uses libvps behind the scenes) would be compatible with this library? This would avoid needing the canvas dependency and the need to write the layers individually to disk just to read them back again.

**Comment by Agamnentzar** [comment]
When reading:

You can use `useImageData: true` option to get 8bpp data instead of canvases
```
  /** Keep image data as byte array instead of canvas.
   * (image data will appear in `imageData` fields instead of `canvas` fields)
   * This avoids issues with canvas premultiplied alpha corrupting image data. */
  useImageData?: boolean;
  ```
You can also use `useRawThumbnail: true` for thumbnails

When writing just fill in `imageData` fields instead of `canvas` fields for each layer

**Comment by richardtallent** [comment]
Thanks for the quick reply! Tried this, just ended up with an empty PSD (284 bytes, invalid):

```js
const psd = {
	width: 10000,
	height: 5000,
	children: [
		{ name: "Left", imageData: await sharp(leftFilename).raw().toBuffer() },
		{ name: "Right", imageData: await sharp(rightFilename).raw().toBuffer() },
	],
};
const buffer = writePsdBuffer(psd);
fs.writeFileSync(psdFilename, buffer);
```

The input files are 5000x5000 8 bit PNG files. The canvas method works, but I actually need to do some extra processing in sharp before writing the images to the PSD file, so I'm trying to avoid another trip to the file system.

My use case: I'm processing left/right stereo 180-degree pairs from a fisheye lens for VR art photography. Fun stuff, but the more I can automate, the better, since there are a ton of steps involved in post-processing. :)

**Comment by Agamnentzar** [comment]
It has to be imageData object:
```ts
interface ImageData {
    data: Uint8ClampedArray;
    height: number;
    width: number;
}
```

**Comment by richardtallent** [comment]
lol... well, I suppose that makes sense!

This did the trick (in case anyone else is looking for this in the future):

```js
const psd = {
	width: 10000,
	height: 5000,
	children: [
		{ name: "Left", imageData: await sharp(leftFilename).raw().toBuffer({ resolveWithObject: true }) },
		{ name: "Right", imageData: await sharp(rightFilename).raw().toBuffer({ resolveWithObject: true }) },
	],
};
```
