### ISSUE TITLE
Using 'Color Burn' Blend Mode Disables 'Transparency Shapes Layer'

### ISSUE THREAD

**Issue by helloar14** [Agamnentzar/ag-psd#101]
Example below generated using code roughly similar to these for the problem layer:

`
{
    left: 0,
    top: 0,
    blendMode: 'color burn',
    opacity: 1,
    transparencyProtected: false,
    hidden: false,
    clipping: false,
    name: 'Name',
    imageData: imageData
}
`

The resulting layer has 'Transparency Shapes Layer' disabled, causing the layer to be marked as 'has advanced blending options'.

![report1](https://user-images.githubusercontent.com/7506276/162932846-551500e3-7762-4816-9760-54f265eb4a86.png)

Is this expected behavior? By default 'Transparency Shapes Layer' is enabled when user does not make any change in Photoshop, which should result in below screenshot:

![report2](https://user-images.githubusercontent.com/7506276/162933589-d6c632fe-c3b4-494a-8db5-6c347dfea064.png)

EDIT: I tried other blending options: Overlay, Soft Light, Multiply, Linear Burn, and Darker Color. So far only Color Burn that produces this problem.

**Comment by Agamnentzar** [comment]
it seems you have to set `blendClippendElements` to `true` not sure why photoshop requires that to work correctly, but that seems to fix the issue

**Comment by helloar14** [comment]
Confirmed. This solution works. Thank you very much!
