### ISSUE TITLE
Convert Uint8Array to base64 does not work!

### ISSUE THREAD

**Issue by gapgag55** [Agamnentzar/ag-psd#102]
How can I convert Uint8Array to base64 without drawing on canvas? 
My attempt is to convert it to buffer and write the file as final, then the output as image cannot be opened 

```
const chunk = psd.linkedFiles[0].data
const buffer = Buffer.from(chunk)
fs.writeFileSync('output.png', buffer)
```

![image](https://user-images.githubusercontent.com/4579539/164153338-1eccbc33-3c01-4133-bb9b-d0970cabb48d.png)

**Comment by Agamnentzar** [comment]
The image is PSB, not PNG. just rename `output.png` to `output.psb` and open it with photoshop

**Comment by gapgag55** [comment]
My expectation is to convert Uint8Array to png. How can I do that?

**Comment by gapgag55** [comment]
Oh got it.  We have to readPsd

```
const buffer = fs.readFileSync('output.psb')
const psd = readPsd(buffer, {});
fs.writeFileSync('output.png', Buffer.from(psd.children[0].canvas.toBuffer()))
```

**Comment by Agamnentzar** [comment]
Yes, you have to read it recursively, you don't need to save it to a file though, you can just read directly from data `const innerPsd = readPsd(psd.linkedFiles[0].data)`
