### ISSUE TITLE
How to distinguish  layer、group、 text 、imgs?

### ISSUE THREAD

**Issue by SunilWang** [Agamnentzar/ag-psd#107]
This package is very powerful.

But I don't know how to distinguish  layer、group、 text 、imgs.

Looking forward to your reply, wish you a happy day。

**Comment by Agamnentzar** [comment]
group - has `children` field and NO `canvas` field
text layer - has `canvas` and `text` fields
smart object leyer - has `canvas` and `placedLayer` fields
layer - has `canvas` field

In general, a good approach is to create PSD file you want to analyze and read it to see what it has inside.

**Comment by SunilWang** [comment]
I want to make a feature  psd to html.

It would be nice to add a "type" distinction.

Are there any plans to add this feature?

**Comment by SunilWang** [comment]
Thank you very much.

I wish you a happy
