### ISSUE TITLE
Is there any documentation for the parsed JOSN field?

### ISSUE THREAD

**Issue by SunilWang** [Agamnentzar/ag-psd#108]
Hello, sorry to bother you again.

There are too many JSON fields parsed out. Is there any detailed documentation?

**Comment by SunilWang** [comment]
Thank you very much.

**Comment by Agamnentzar** [comment]
@SunilWang I added some basic documentation for the PSD object here: https://github.com/Agamnentzar/ag-psd/blob/master/README_PSD.md
