### ISSUE TITLE
Canvases accessed through readPsd() don't have filters applied

### ISSUE THREAD

**Issue by tcaruth** [Agamnentzar/ag-psd#112]
I have a psd that contains a vector smart object layer at 7% opacity and with a color mask. If I output the layer canvases as png files, the color mask and opacity are not applied to the exported image. Does this functionality exist? Is it just my very specific use case that isn't working?

```js
const fs = require('fs')
const ag = require('ag-psd');
require('ag-psd/initialize-canvas')

const buffer = fs.readFileSync('test.psd')
const psd = ag.readPsd(buffer)
fs.writeFileSync('output.png', psd.children[2].canvas.toBuffer('image/png', {compressionLevel: 6}))

```

[test.psd.zip](https://github.com/Agamnentzar/ag-psd/files/9103621/test.psd.zip)
[output](https://user-images.githubusercontent.com/7960869/178770891-625d86a2-5420-4fa1-8aa7-5a2325f8cd4b.png)

**Comment by Agamnentzar** [comment]
This library only reads the bitmaps that are saved in the file, PSD file contains the raw state of each bitmap layer, if you want to bitmap with all the effects applied you'll need to apply them yourself. Both opacity and mask should be relatively easy to apply using [Canvas API](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) with `node-canvas`.

**Comment by tcaruth** [comment]
Thanks @Agamnentzar, appreciate your work
