### ISSUE TITLE
how to get real vector mask shape

### ISSUE THREAD

**Issue by houhuiyao1** [Agamnentzar/ag-psd#114]
The vector mask is a white background
![image](https://user-images.githubusercontent.com/63383735/181418281-27d87fa8-e65d-46aa-bfbb-7f10bc3d9688.png)
And I can get vector mask path , but the path seems incomplete，I can't know the line is curve
![image](https://user-images.githubusercontent.com/63383735/181418512-6e595095-9a16-4dc3-8dd9-516a4b78037e.png)
What can I do to get the real vector mask shape to compose and clip two canvas，

**Comment by Agamnentzar** [comment]
Each of the knots represents point with 2 control handles like this 

![image](https://user-images.githubusercontent.com/572298/181419295-c5563eb0-6647-4da5-89ff-adbb849a83ff.png)

So it's x & y of 1st control point, then x & y of the actual point and then x & y 2nd control point 

The basic idea is that photoshop has:
`control-point -> point -> control-point`
and in HTML canvas you have
`control-point -> control-point -> point`
You can use it like this
`context.bezierCurveTo(cp1x, cp1y, cp2x, cp2y, x, y)`

**Comment by houhuiyao1** [comment]
> Each of the knots represents point with 2 control handles like this
> 
> ![image](https://user-images.githubusercontent.com/572298/181419295-c5563eb0-6647-4da5-89ff-adbb849a83ff.png)
> 
> So it's x & y of 1st control point, then x & y of the actual point and then x & y 2nd control point
> 
> The basic idea is that photoshop has: `control-point -> point -> control-point` and in HTML canvas you have `control-point -> control-point -> point` You can use it like this `context.bezierCurveTo(cp1x, cp1y, cp2x, cp2y, x, y)`

yeah！thank you！it seems work.but I don't know if it's my reason. Aftrer parsing the curve is different.
This is the original：
![image](https://user-images.githubusercontent.com/63383735/181450632-df789e47-825b-4d02-b147-f9b4db71bebf.png)
And this is the result
![image](https://user-images.githubusercontent.com/63383735/181450885-131800c7-74be-4614-80de-29aad941796b.png)
Did I do something wrong...

**Comment by Agamnentzar** [comment]
paste your code and I'll check it

**Comment by houhuiyao1** [comment]
> paste your code and I'll check it

that's my code:
  const {canvas} = layer
  const newCanvas = document.createElement('canvas')
  const ctx = newCanvas.getContext('2d')
  if(layer.mask && layer.vectorMask){
    newCanvas.width = canvas!.width
    newCanvas.height = canvas!.height
    const knots = layer.vectorMask.paths[0]?.knots.map(it=>{
      const newPoints = it.points.map((point,index)=>{
        if(index%2 === 0){
          return point - layer.left!
        }else{
          return point - layer.top!
        }
      })
      return {...it, points : newPoints}
    })

    ctx?.beginPath()
    for(let i = 0;i<knots.length;i++){
        const cp1x = Math.floor(knots[i].points[0])
        const cp1y = Math.floor(knots[i].points[1])
        const cp2x = Math.floor(knots[i].points[4])
        const cp2y = Math.floor(knots[i].points[5])
        const x = Math.floor(knots[i].points[2])
        const y = Math.floor(knots[i].points[3])
        ctx?.bezierCurveTo(cp1x, cp1y, cp2x, cp2y, x, y)
    }
    ctx?.closePath()
    ctx?.clip()
    ctx?.drawImage(canvas!, 0, 0)
    return newCanvas
  }

**Comment by houhuiyao1** [comment]
> paste your code and I'll check it

that's my code:
const {canvas} = layer
  const newCanvas = document.createElement('canvas')
  const ctx = newCanvas.getContext('2d')
  if(layer.mask && layer.vectorMask){
    newCanvas.width = canvas!.width
    newCanvas.height = canvas!.height
    const knots = layer.vectorMask.paths[0]?.knots.map(it=>{
      const newPoints = it.points.map((point,index)=>{
        if(index%2 === 0){
          return point - layer.left!
        }else{
          return point - layer.top!
        }
      })
      return {...it, points : newPoints}
    })

    ctx?.beginPath()
    for(let i = 0;i<knots.length;i++){
        const cp1x = Math.floor(knots[i].points[0])
        const cp1y = Math.floor(knots[i].points[1])
        const cp2x = Math.floor(knots[i].points[4])
        const cp2y = Math.floor(knots[i].points[5])
        const x = Math.floor(knots[i].points[2])
        const y = Math.floor(knots[i].points[3])
        ctx?.bezierCurveTo(cp1x, cp1y, cp2x, cp2y, x, y)
    }
    ctx?.closePath()
    ctx?.clip()
    ctx?.drawImage(canvas!, 0, 0)
    return newCanvas
  }

**Comment by houhuiyao1** [comment]
> paste your code and I'll check it

that's my code and thank you:
  const {canvas} = layer
  const newCanvas = document.createElement('canvas')
  const ctx = newCanvas.getContext('2d')
  if(layer.mask && layer.vectorMask){
    newCanvas.width = canvas!.width
    newCanvas.height = canvas!.height
    const knots = layer.vectorMask.paths[0]?.knots.map(it=>{
      const newPoints = it.points.map((point,index)=>{
        if(index%2 === 0){
          return point - layer.left!
        }else{
          return point - layer.top!
        }
      })
      return {...it, points : newPoints}
    })
    ctx?.beginPath()
    for(let i = 0;i<knots.length;i++){
        const cp1x = Math.floor(knots[i].points[0])
        const cp1y = Math.floor(knots[i].points[1])
        const cp2x = Math.floor(knots[i].points[4])
        const cp2y = Math.floor(knots[i].points[5])
        const x = Math.floor(knots[i].points[2])
        const y = Math.floor(knots[i].points[3])
        ctx?.bezierCurveTo(cp1x, cp1y, cp2x, cp2y, x, y)
    }
    ctx?.closePath()
    ctx?.clip()
    ctx?.drawImage(canvas!, 0, 0)
    return newCanvas
  }

**Comment by houhuiyao1** [comment]
> paste your code and I'll check it

that's my code and thank you:
```javaScript
const {canvas} = layer
  const newCanvas = document.createElement('canvas')
  const ctx = newCanvas.getContext('2d')
  if(layer.mask && layer.vectorMask){
    newCanvas.width = canvas!.width
    newCanvas.height = canvas!.height
    const knots = layer.vectorMask.paths[0]?.knots.map(it=>{
      const newPoints = it.points.map((point,index)=>{
        if(index%2 === 0){
          return point - layer.left!
        }else{
          return point - layer.top!
        }
      })
      return {...it, points : newPoints}
    })
    ctx?.beginPath()
    for(let i = 0;i<knots.length;i++){
        const cp1x = Math.floor(knots[i].points[0])
        const cp1y = Math.floor(knots[i].points[1])
        const cp2x = Math.floor(knots[i].points[4])
        const cp2y = Math.floor(knots[i].points[5])
        const x = Math.floor(knots[i].points[2])
        const y = Math.floor(knots[i].points[3])
        ctx?.bezierCurveTo(cp1x, cp1y, cp2x, cp2y, x, y)
    }
    ctx?.closePath()
    ctx?.clip()
    ctx?.drawImage(canvas!, 0, 0)
    return newCanvas
  }
```

**Comment by Agamnentzar** [comment]
Ok, so a little bit more details: in photoshop knots relate to points, but in HTML canvas it's curves with control points. to draw a curve you need one control point from previous knot, like this:

```
        const cp1x = Math.floor(knots[i - 1].points[0])
        const cp1y = Math.floor(knots[i - 1].points[1])
        const cp2x = Math.floor(knots[i].points[4])
        const cp2y = Math.floor(knots[i].points[5])
        const x = Math.floor(knots[i].points[2])
        const y = Math.floor(knots[i].points[3])
        ctx?.bezierCurveTo(cp1x, cp1y, cp2x, cp2y, x, y)
```

So you'll have to start from 2nd knot, not the first one, and then ad the end wrap it back to the first knot

**Comment by Agamnentzar** [comment]
You probably also shouldn't floor the coordinates, that will distort the shape.

**Comment by houhuiyao1** [comment]
> Ok, so a little bit more details: in photoshop knots relate to points, but in HTML canvas it's curves with control points. to draw a curve you need one control point from previous knot, like this:
> 
> ```js
>         const cp1x = Math.floor(knots[i - 1].points[4])
>         const cp1y = Math.floor(knots[i - 1].points[5])
>         const cp2x = Math.floor(knots[i].points[0])
>         const cp2y = Math.floor(knots[i].points[1])
>         const x = Math.floor(knots[i].points[2])
>         const y = Math.floor(knots[i].points[3])
>         ctx?.bezierCurveTo(cp1x, cp1y, cp2x, cp2y, x, y)
> ```
> 
> So you'll have to start from 2nd knot, not the first one, and then ad the end wrap it back to the first knot

thank you so much ,you tips are very useful ! I‘m very new to PS, very sorry and I have a little question here.
I found a very strange problem，It seems that the last curve is a little wrong
![image](https://user-images.githubusercontent.com/63383735/181700497-750d51a6-378d-4bc9-ae1d-9cb2d179cd58.png)
and here is my code:
```javascript
ctx?.beginPath()
    for(let i = 0;i<knots.length;i++){
        const preIndex = i === 0?knots.length - 1:i - 1
        const cp1x = knots[preIndex].points[4]
        const cp1y = knots[preIndex].points[5]
        const cp2x = knots[i].points[0]
        const cp2y = knots[i].points[1]
        const x = knots[i].points[2]
        const y = knots[i].points[3]
        ctx?.bezierCurveTo(cp1x, cp1y, cp2x, cp2y, x, y)
    }
    ctx?.closePath()
    ctx?.clip()
    ctx?.drawImage(canvas!, 0, 0)
    return newCanvas
```

**Comment by Agamnentzar** [comment]
You need to set the starting point correctly before starting the loop:
```js
ctx?.moveTo(knots[knots.length - 1].points[2], knots[knots.length - 1].points[3])
```

**Comment by houhuiyao1** [comment]
> You need to set the starting point correctly before starting the loop:
> 
> ```js
> ctx?.moveTo(knots[knots.length - 1].points[2], knots[knots.length - 1].points[3])
> ```

it works! thank you very much
