### ISSUE TITLE
Using read psd function in browser (html)

### ISSUE THREAD

**Issue by SpectreCerberus** [Agamnentzar/ag-psd#116]
Apologies for the newby question. Recently started with html, js and ts. 

How would one go about reading layers from psd files in order to use them separately on a canvas in html?

**Comment by Agamnentzar** [comment]
check out this code snippet for downloading and reading the PSD file https://github.com/Agamnentzar/ag-psd#reading-1 

The `psd.children[0].canvas` at the end is a regular HTMLCanvasElement that can be drawn on any other canvas

**Comment by SpectreCerberus** [comment]
I am unable to have the canvas be drawn by the append child.
I changed the following: xhr.open('GET', 'Images/src.psd', true); to point towards where I saved the psd.

At the end I want to give the ability to pick layers to disply, but currently I can't seem to get the psd as a whole to work.

My thought is perhaps I'm pointing to the img in the wrong manner but I tried "./Images/src.psd" as well and didn't work.

**Comment by Agamnentzar** [comment]
To read it this way you have to serve it on your server along with the html file, so make sure that the file is available at that URL when you type it in the browser. Also check development tools console in your browser for any errors.

**Comment by SpectreCerberus** [comment]
The files are available as testing is just done on my local (vm)

**Comment by Agamnentzar** [comment]
Any errors in the console ? Also the example only shows first layer canvas so make sure you're testing with PSD file that has something on the first layer (the one at the bottom in Photoshop layer panel)

**Comment by SpectreCerberus** [comment]
So been looking around, I think I made a mistake in my js file "Cannot use import statement outside a module"
As for the layers, how would I go about looking at different layers? (Also the src.psd is from your testing folder, thank you for providing test psd's!)

**Comment by Agamnentzar** [comment]
You can use the library without using import statements, by including bundled version

```
<script src="node_modules/ag-psd/dist/bundle.js"></script>
<script>
  var readPsd = agPsd.readPsd;
  // rest the same as above
</script>
```

You can see the structure of the returned object here: https://github.com/Agamnentzar/ag-psd/blob/master/src/psd.ts#L935

Or read through detailed explanation of all the fields here: https://github.com/Agamnentzar/ag-psd/blob/master/README_PSD.md

But basically the `children` property is an array of all top-level layers and layer groups, so you just iterate over it, and then each layer group will have its own `children` property with its sublayers, so you have to read it recursively.

**Comment by SpectreCerberus** [comment]
Part of troubleshooting at this point (thanks for the active help on a sunday btw)
the console.log doesn't seem to be writing anything, so I'm assuming somewhere the script as a whole isn't even running and that's perhaps why I am not seeing output?

**Comment by Agamnentzar** [comment]
can you show your code so far ?

**Comment by SpectreCerberus** [comment]
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Char creator proto</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <script src="node_modules/ag-psd/dist/bundle.js"></script>
        <script>
          var readPsd = agPsd.readPsd;
          // rest the same as above
          const xhr = new XMLHttpRequest();
          xhr.open('GET', 'Images/src.psd', true);
          xhr.responseType = 'arraybuffer';
          xhr.addEventListener('load', function () {
            const buffer = xhr.response;
            const psd = readPsd(buffer);

            console.log(psd);
            
            document.body.appendChild(psd.children[0].canvas);
          }, false);
          xhr.send();
        </script>
        
        <link rel="stylesheet" href="./Styles/Dropdown.css">
        
    </head>
    <body>
            
        <ul>
            <li><a href="#home">Home</a></li>
            <li><a href="#news">News</a></li>
            <li class="dropdown">
              <a href="javascript:void(0)" class="dropbtn">Dropdown</a>
              <div class="dropdown-content">
                <a onclick="LoadingImg()">Link 1</a>
                <a href="#" onclick="fuckIt()">Link 2</a>
                <a href="#">Link 3</a>
              </div>
            </li>
        </ul>
          
          <h3>Dropdown Menu inside a Navigation Bar</h3>
          <p>Hover over the "Dropdown" link to see the dropdown menu.</p>
        
        <div align="center">
            <canvas id="ProtoPSD" style="border: 5px solid #000000;"></canvas>
        </div>
        

        
    </body>
</html>

**Comment by SpectreCerberus** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/101086930/185800121-f4c8e280-9662-4abd-8513-a34d7cbb2144.png)

**Comment by Agamnentzar** [comment]
Use `agPsd.readPsd` instead of `readPsd` when you're using bundle version. Other than that it worked fine for me. Also make sure you're serving the files with some local server and not just opening the HTML file directly in the browser.

**Comment by Agamnentzar** [comment]
It worked fine for me. Also make sure you're serving the files with some local server and not just opening the HTML file directly in the browser.

**Comment by SpectreCerberus** [comment]
That worked, guess my mistake was simply using F5 in VS code. I'll play around more, thanks for the help.
On the child topic before I close, is there a way to read the label of a layer. Say it's labeled as "Head". For the purposes of sorting into dropdowns.

**Comment by Agamnentzar** [comment]
Each layers has a `name` property, I think that's what you're looking for.

**Comment by SpectreCerberus** [comment]
Sweet!! Thanks, I'll give that a go! Have a great evening!

**Comment by SpectreCerberus** [comment]
So having the canvas work for me finally...how do you use the layer name if psd.children[0] shows the base layer, but using the name seems to not come up with intellisense.

**Comment by Agamnentzar** [comment]
The name should be in `psd.children[0].name`. Intellisense will only work properly if you're working with typescript. In javascript mode it can only make guesses as to types of variables.

**Comment by SpectreCerberus** [comment]
![image](https://user-images.githubusercontent.com/101086930/188919936-a833c5ce-1c66-474a-a52a-be907ffc74c8.png)
I see, I'll give ts a try perhaps... how would you write this layer name then? psd.children['Layer 0'].name?

**Comment by Agamnentzar** [comment]
- `psd.children[0].name` to get the name
- `psd.children[0].name = "new name"` to set the name
- `const layer = psd.children.find(layer => layer.name === 'Layer 0');` to find layer by name

**Comment by SpectreCerberus** [comment]
Ah okay I see what you mean. Thanks
