### ISSUE TITLE
Needing some advice as searches only come up with TS, non usefull.

### ISSUE THREAD

**Issue by SpectreCerberus** [Agamnentzar/ag-psd#117]
What I need assistance with is just an explanation of: document.body.appendChild(psd.children[0].canvas);
Specifically I am trying to append to a static canvas, as I want to have the ability to add/remove layers of a psd to recreate custom images on a canvas. I'm just having trouble finding documentation on the functions to understand how I can use it.

**Comment by Agamnentzar** [comment]
You can find documentation of web api on MDN, documentation for `appendChild` is here: https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild

But in this example I used `appendChild` only to quickly show that the PSD is loaded correctly. If you want to actually render PSD contents you'll have to create main Canvas element and draw all of the layers on it using 2d render api: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API You'll then mainly just use `drawImage` function to draw the layers on the main canvas.

This should work for all the basic features like layer blending modes, groups, etc. But if you need to support special layers like adjustment layers or layer effects, then you'll have to manually calculate pixels for these effects.

**Comment by SpectreCerberus** [comment]
Sorry about this but could I ask for another pointer? I've been diving into using the canvas and 2d render api and I think I have it...but I can't draw the image. I've tried ctx.drawImage(psd.children[0]); and ctx.drawImage(psd.children[0].mycanvas); 
"mycanvas" being a declared canvas for testing. I know ctx.drawImage(Image) works, am I using "psd.children[0].mycanvas" wrong?

**Comment by Agamnentzar** [comment]
it should be `ctx.drawImage(psd.children[0].canvas)`

**Comment by SpectreCerberus** [comment]
Okay, I'm pretty sure I'm being a dunce then. My following code is running in a function, am I missing something obvious or just showing my green roots?

function read2(){
          var readPsd = agPsd.readPsd;
          const mycanvas = document.getElementById('ProtoPSD');
          const ctx = mycanvas.getContext('2d');

          const xhr = new XMLHttpRequest();
          xhr.open('GET', './Images/src.psd', true);
          xhr.responseType = 'arraybuffer';
          xhr.addEventListener('load', function(){
            const buffer = xhr.response;
            const psd = readPsd(buffer)

            ctx.drawImage(psd.children[0].canvas);
          });
          xhr.send();
        }

**Comment by Agamnentzar** [comment]
add `console.log(psd)` before drawImage and see if you get proper structure logged in the console. Also make sure the canvas is big enough to actually draw the layer and make sure that the first layer in your PSD file has something on it, sometimes first layer is just white background and you'll just fill your canvas with white.

You can also try `ctx.drawImage(psd.canvas);` as a test, this will draw composite canvas that combines all the layers.

**Comment by SpectreCerberus** [comment]
Thanks, I used the console and that did the trick..... like a dum dum I forgot drawImage takes 3 arguments at least (img, 0, 0)
