### ISSUE TITLE
Layers are in reverse order.

### ISSUE THREAD

**Issue by YegorUdovchenko** [Agamnentzar/ag-psd#118]
Hello. I'm trying to figure out is this a bug or an expected behavior. I generate a PSD file with multiple layers and pass them in the particular order, e.g. "Layer 1", "Layer 2", "Layer 3". Then I open this file with a PSD viewer and see layers in the reverse order like this:
![Screenshot 2022-08-30 122624](https://user-images.githubusercontent.com/33632314/187404618-ced8b11e-f10c-4999-b340-28f99145cd28.png)

When I then read this file with your utility, the layers still have the correct order: "Layer 1", "Layer 2", "Layer 3".

I'm using the latest 14.5.3 version.

Can you please tell whether it is expected behavior or not. Thank you.

**Comment by Agamnentzar** [comment]
the library reads and writes the layers in the same order that the PSD file stores them, and it's the draw order of the layers. So it's from bottom up.

**Comment by YegorUdovchenko** [comment]
Thank you for the quick answer.
