### ISSUE TITLE
Package broken?

### ISSUE THREAD

**Issue by Spring7331** [Agamnentzar/ag-psd#119]
Im using ES6 for imports 

Error: Cannot find module 'canvas'
on import 'ag-psd/initialize-canvas';

Edit - Just tried with TS aswell same issue

Error: Cannot find module 'canvas'
Require stack:
....

**Comment by Agamnentzar** [comment]
did you install `canvas` module ?

**Comment by Spring7331** [comment]
I apologize I didnt see that thank you
