### ISSUE TITLE
Frontend bug, there is no Image in canvas_1

### ISSUE THREAD

**Issue by Nemethe** [Agamnentzar/ag-psd#12]
I found a bug on the frontend.
In /ag-psd/dist/initializeCanvas.js line 6
There is no Image in canvas_1
I deleted `canvas_1` from `var image = new canvas_1.Image();`
and leave `var image = new Image();` to solve this problem for me.

**Comment by Agamnentzar** [comment]
`initializeCanvas.js` is only used in nodejs environment, you shouldn't include the file when running in browser

**Comment by Nemethe** [comment]
tnx
