### ISSUE TITLE
Exporting

### ISSUE THREAD

**Issue by Spring7331** [Agamnentzar/ag-psd#120]
Is it possible to export the PSD as json to use for editing? It seems like the image only updates after I rotate or click the text in photopea/photoshop

Wondering can I statically load the JSON file and edit and write it from there?

**Comment by Agamnentzar** [comment]
This library doesn't generate new layer images for you, you need to update them yourself, you can read more about it here: https://github.com/Agamnentzar/ag-psd#modifying-documents and here: https://github.com/Agamnentzar/ag-psd#updating-text-layers

**Comment by Spring7331** [comment]
Thank you
