### ISSUE TITLE
How to analyze the effect in psd, such as color overlay, which is not resolved after being converted into an image

### ISSUE THREAD

**Issue by keepGoinging** [Agamnentzar/ag-psd#123]

**Comment by Agamnentzar** [comment]
You'd have to figure out how Photoshop renders it and compute it yourself unfortunately. This library only provides means for reading and writing the PSD file, it can't do the rendering part, sorry.

**Comment by kstulgys** [comment]
I have same issue. What could be a possible solution? Like where to start? The end result for me is to export modified psd in an image.

**Comment by Agamnentzar** [comment]
@kstulgys You'd have to replicate entire rendering engine of Photoshop, which is much larger project than this library is. If your goal is to generate images from some template, depending on what are your requirements maybe better solution is to use something like node-canvas and just create a function that draws the image that you want and saves it as PNG. See if this is something that fits your needs: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial
