### ISSUE TITLE
Converting PSD to Other Formats?

### ISSUE THREAD

**Issue by daviss92** [Agamnentzar/ag-psd#124]
From what I gather from the documentation, you can get the image as buffer and/or save as PNG.

But from my experience with my testing via NodeJS, the documentation isn't lining up for me. Does anyone have an idea what I'm doing wrong? Ideally I just want to get a buffer of the image.

```
let psd = readPsd(fs.readFileSync('/path/to.file', { useImageData: true }));

//Below attempts Fails
let buff = psd.children[0].canvas.toBuffer();
let buff = psd.canvas.transferToImageBitmap();
```

**Comment by Agamnentzar** [comment]
When you set `useImageData: true` you get `imageData` fields instead of `canvas` fields. You can remove `useImageData: true` to get canvas fields instead.

**Comment by daviss92** [comment]
I had originally tried that, but I still feel like I'm missing something here?

let psd = readPsd(fs.readFileSync('/path/to.file'));
let buff = psd.children[0].canvas.toBuffer();

Results in **Cannot read properties of undefined (reading 'toBuffer')**

let psd = readPsd(fs.readFileSync('/path/to.file'));
let buff = psd.canvas.transferToImageBitmap();

Results in **undefined is not a function**

**Comment by Agamnentzar** [comment]
What is the structure the layers in your PSD file? Maybe you're trying to get canvas from layer group.

**Comment by daviss92** [comment]
Ah, maybe I was miss-understanding. I was kind of looking to just take the whole document (canvas) and save that as an image.

Sort of like a File > save-as or Export from Photoshop.

**Comment by Agamnentzar** [comment]
You can do that by using `psd.canvas`

**Comment by daviss92** [comment]
Okay, that seems to work! But just to clarify, the buffer is in PNG format?

**Comment by Agamnentzar** [comment]
Yes, by default it's PNG, you can pass it an argument to get other format, full help for the function can be found here: https://github.com/Automattic/node-canvas#canvastobuffer

**Comment by daviss92** [comment]
Great! I didnt see the canvas component. Thanks for this.
