### ISSUE TITLE
Capturing layer changes over animation frames?

### ISSUE THREAD

**Issue by calingribble** [Agamnentzar/ag-psd#126]
Say I am reading from layer 1 and animation frame 1 is enabled.

If the `top` and `left` value for layer 1 changes from animation frame 1 to animation frame 2, how could I capture this?

**Comment by Agamnentzar** [comment]
I think it will be in `layer.animationFrames[0].offset` like here: https://github.com/Agamnentzar/ag-psd/blob/master/test/read/animation-offset/data.json#L216 but you'll have to check how the structure of your document looks like when read
