### ISSUE TITLE
Re-Rendering the Composite Image after Smart Object with new Buffer

### ISSUE THREAD

**Issue by zkschmitz** [Agamnentzar/ag-psd#128]
I feel like I am really close but am just missing one last step. I am taking a PSD with a smart layer and then trying to change the bite array to get a different image. The below code works well for me to get the image and place it in the PSD file. I can then open the new PSD file and I can see the new image in the Smart Object placeholder. However, when I try to write the new PSD file to buffer, I am getting the old composite image. I saw in the documentation that it won't re-render the bitmap unless I force it but I am unable to do so. Any help would be greatly appreciated!  

My code so far: 
```
import * as path from "path";
import * as fs from "fs";
import "ag-psd/initialize-canvas.js"; // only needed for reading image data and thumbnails
import { readPsd, writePsdBuffer } from "ag-psd";
import { createCanvas, Image } from "canvas";

function loadCanvasFromFile(filePath) {
  const img = new Image();
  img.src = fs.readFileSync(filePath);
  const canvas = createCanvas(img.width, img.height);
  canvas.getContext("2d").drawImage(img, 0, 0);
  return canvas;
}

async function main() {
  const buffer = fs.readFileSync("mockup-template.psd");

  // read only document structure
  const psd1 = readPsd(buffer, {});
  const smart_object_layer = psd1.children.find((layer) => layer.name === "mm_wrp:shirt_image");
  const linked_layer = psd1.linkedFiles.find((layer) => layer.id === smart_object_layer.placedLayer?.id);

  const file_path = "smart-object-layer.png";
  const image = fs.readFileSync(file_path);
  smart_object_layer.canvas = loadCanvasFromFile(file_path);
  linked_layer.data = image;

  const new_buffer = writePsdBuffer(psd1, { generateThumbnail: false, trimImageData: true, logMissingFeatures: true });
  const result = readPsd(new_buffer.buffer, { skipLayerImageData: true, logMissingFeatures: true, throwForMissingFeatures: true });
  fs.writeFileSync("output_psd.psd", new_buffer);
  fs.writeFileSync("altered-image.png", result.canvas.toBuffer());
}

main();
```

**Comment by Agamnentzar** [comment]
Unfortunately this library can't render the document, so if you want to update the composite image (and also pre-rendered layer image) after changing the smart object you need to draw them yourself using regular canvas api.

**Comment by zkschmitz** [comment]
Wow, thank you so much for the quick response!

Any places you can point me to that might be able to help me with this?

**Comment by Agamnentzar** [comment]
you can use createCanvas function that you have there and that will give you a canvas that behaves similar to regular HTML canvas element, you can get drawing context from it using `canvas.getContext('2d')` that will behave the same as in browser, you can get full help here: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D Unfortunately if you have some warps there for the image it you might need to implement processing of those pixel by pixel because regular canvas doesn't have any support for that.

**Comment by zkschmitz** [comment]
Amazing! This is a great tip. I'll dig into it but I appreciate you answering this question more directly (I see you've answered it a ton in the issue board/documentation so I appreciate the time to answer it again... 😃)

**Comment by kstulgys** [comment]
So anyways, how to rerender canvas so 
`fs.writeFileSync("altered-image.png", result.canvas.toBuffer());`
produces an updated image?

**Comment by Agamnentzar** [comment]
@kstulgys this library does not implement re-rendering the updated layer images or composite image, sorry. It can only read and write data structure of the file.

**Comment by jaankoppe** [comment]
> Amazing! This is a great tip. I'll dig into it but I appreciate you answering this question more directly (I see you've answered it a ton in the issue board/documentation so I appreciate the time to answer it again... 😃)

@zkschmitz, There's an API for that. maybe this helps: https://github.com/Agamnentzar/ag-psd/issues/147#issuecomment-1663964082
