### ISSUE TITLE
How can I extract multi layers and output one image?

### ISSUE THREAD

**Issue by CavellHuang** [Agamnentzar/ag-psd#129]
Is there any way I can select multi layers and composite them as one image?

**Comment by Agamnentzar** [comment]
The PSD file contains image for each layer and a composite image of the entire drawing. If you want to create composite image of only some of the layers, you'd have to composite them yourself, probably using something like node-canvas (or HTML canvas element in a browser)

**Comment by CavellHuang** [comment]
> 

Can I do it by modifying psd document such as set the layer I don't want to output hidden, or use the layer canvas that psd document already had.

**Comment by Agamnentzar** [comment]
You can read canvas of each layer and composite canvas of the whole document from the PSD file, but if you modify the document the canvases will no longer be correct and you have to update them yourself this library will not modify them for you. You can't modify the document and then read the composite canvas because it will be the old version of the canvas.

**Comment by CavellHuang** [comment]
> You can read canvas of each layer and composite canvas of the whole document from the PSD file, but if you modify the document the canvases will no longer be correct and you have to update them yourself this library will not modify them for you. You can't modify the document and then read the composite canvas because it will be the old version of the canvas.



> You can read canvas of each layer and composite canvas of the whole document from the PSD file, but if you modify the document the canvases will no longer be correct and you have to update them yourself this library will not modify them for you. You can't modify the document and then read the composite canvas because it will be the old version of the canvas.

Wath bothers me is how should I update the composite canvas if I modify the document. Do you have any ideas? Thanks so much!

**Comment by Agamnentzar** [comment]
If the document is very simple you can use basic functionality of HTML canvas (or node-canvas in nodejs) https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial

If the document is complex and uses more features you'll have to reimplement portions or entirety of Photoshop rendering engine.

**Comment by CavellHuang** [comment]
> If the document is very simple you can use basic functionality of HTML canvas (or node-canvas in nodejs) https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial
> 
> If the document is complex and uses more features you'll have to reimplement portions or entirety of Photoshop rendering engine.

ok, I will try it. Thanks again for your answer.
