### ISSUE TITLE
Saving Text Layers' Modifications as a PNG File.

### ISSUE THREAD

**Issue by cnjw2021** [Agamnentzar/ag-psd#130]
Hello,

I want to read a PSD file and modify the texts value of each Text Layer. I know that it is impossible to apply this modification to a PSD file. How about the modification of the Text Layer applied when saving the PSD as a png file?

Thanks, in advance.

**Comment by Agamnentzar** [comment]
This library only reads and writes the PSD file, it can't render text layers, so you can't use it to generate new version of bitmap of the text layer as it requires reimplementing entire rendering engine of Photoshop. If you just want to generate PNGs with some text and images maybe using HTML canvas or node-canvas is a better fit for you: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial
