### ISSUE TITLE
Creating new PSD with transformed smart layers

### ISSUE THREAD

**Issue by lookitsash** [Agamnentzar/ag-psd#133]
Using this library, can I build PSDs from scratch with smart object layers (having the smart object linked files embedded into the PSD), and also apply basic x/y/rotation transformations to the smart objects?

My use case is: I built a web UI where users can build tshirt designs from their uploaded images, and move/rotate the various images. I'm saving as JSON object and need to be able to re-create their design in photoshop. I tried using Adobe Photoshop API but its super buggy, and came across this library.

**Comment by Agamnentzar** [comment]
Yes you can do it, but this library can't generate the layer bitmaps, so you'd have to draw them yourself, it should be pretty simple if you're only doing basic transformations.

**Comment by lookitsash** [comment]
Awesome thanks.  I will try what you suggested.

**Comment by lookitsash** [comment]
I opened a sample PSD, and was able to update the transform data (psdFile.children[x].placedLayer.transform)  to apply a rotation, and re-save the PSD.  As you pointed out though, the bitmap does not update in Photoshop. As soon as I activated the Free Transform tool though in Photoshop, the new rotation I made in code kicked in and rotated the image visually.

I would like to update the layer bitmap in code so it shows correctly in Photoshop right away.  Could you point me in the right direction for how I can go about replacing the layer bitmap using your library (assuming I take care of rotating the bitmap myself), without actually modifying the source smart object linked file?

Great library BTW.

**Comment by Agamnentzar** [comment]
Use `layer.canvas` property, you can replace it with new canvas using https://github.com/Automattic/node-canvas library. You just need to obtain bitmap representation from your smart object file and then draw it onto the new canvas. Also remember to adjust layer.left/right/top/bottom to match the new size of the canvas.

**Comment by lookitsash** [comment]
Everything is working great with the canvases. One small thing I've noticed though is that the custom generated canvases sometimes cause a very slight color tone change to the images compared to what Photoshop produces.  

Here's what I did:
1. Created a sample PSD in code with a smart object layer, creating a canvas and drawing the image on the canvas
2. Opened the PSD in Photoshop
3. When I select the layer and hit Ctrl-T (to enable Free Transform), Photoshop "rebuilds" the canvas from the linked file, and the color tone changes very slightly. When I cancel Free Transform, the original canvas i created re-applies and color tone reverts.

See attached screenshots from Photoshop - LEFT image is from canvas created in code. RIGHT image is when I activate Free Transform mode.  The RIGHT image is a little brighter.

![PS Canvas Compare](https://user-images.githubusercontent.com/10585301/235569884-252861ff-4da3-446d-9012-57bc403c3785.jpg)

It's not a huge deal, as the color tone shift is very minor, and only noticeable on certain shades of color. I'm just trying to get a custom made PSD as close as possible to what Photoshop generates, so curious if you had any ideas on whats happening.

**Comment by Agamnentzar** [comment]
Not really sure what exactly is happening. One issue might be that your source file has some color profile information in it that is not interpreted correctly by node-canvas library. I don't think it would have anything to do with scaling, because your have big parts of the image with the same color, and that should give the same result no matter what scaling algorithm is used. I really don't know how color profile work and how to deal with them, but a quick test would be to just use some converter that can strip color profile information and check if that results in the same colors.

**Comment by lookitsash** [comment]
I think you were right about the color profile stuff.  I figured it out. The image was taken on an iPhone and has a Display P3 color profile. I use the Sharp library to convert to standard sRgb before drawing to the canvas and the issue was resolved.

**Comment by lookitsash** [comment]
Last question I promise, as everything is working great so far with the library and i'm almost done solving my use case.  I created a PSD with multiple layers. Now I want to trim the excess space in the canvas, so all layers touch the edge of the document.  I can do this just by changing the document size and moving the layer coords to adjust for the new document size, but was just curious if there was something already in this library to handle re-sizing the canvas (like how photoshop lets you resize the canvas with relative positioning of the existing items) ?

**Comment by YCanvas** [comment]
@lookitsash Im trying to achieve something similar, is it possible to share your code for the library not UI?
