### ISSUE TITLE
When I export SVG, I got a blank gap issue with SVG。 

### ISSUE THREAD

**Issue by zhyyangyang** [Agamnentzar/ag-psd#139]
![svg_issue](https://github.com/Agamnentzar/ag-psd/assets/1292113/10ff1da3-23fd-470f-a48f-a3d8234be1fc)

`for (const path of paths) {
        pathString += `<path d=" `;
        let pathD = '';
        const knots = path.knots;
        const startPoint = knots[0].points;
        pathD += `M${startPoint[2]} ${startPoint[3]} `;
        for (let i = 0; i < knots.length; i++) {
            const points = knots[i].points,
                nPoints = i < knots.length - 1 ? knots[i + 1].points : startPoint;
            if (i === knots.length - 1) {
                pathD += ` C ${points[4]},${points[5]} ${startPoint[0]},${startPoint[1]} ${startPoint[2]},${startPoint[3]} Z`;
            } else {
                pathD += ` C ${points[4]},${points[5]} ${nPoints[0]},${nPoints[1]} ${nPoints[2]},${nPoints[3]}`;
            }
        } 
        pathString += `${pathD} " ${colorStr} ${borderStr}/>`;
    }`

**Comment by zhyyangyang** [comment]
> `linked` means if the control points are moving together or not, it doesn't matter for rendering. You need to put all points in the same path according to the `operation` value, in case of `combine` you just need to add the new points to existing path and it should be fine if the winding is set correctly in svg. There are other operations like subtract or exclude that would require doing more complex operations on the paths but in your case you just need to put all the points on a single SVG path.

problem solved ,thank you so much~

**Comment by zhyyangyang** [comment]
hello,Sorry to bother you again.  When I  put all points in the same path. I got wrong result in this svg. 

![debug](https://github.com/Agamnentzar/ag-psd/assets/1292113/534a4585-47dd-42cc-ba34-0c49bad98aaa)
![test](https://github.com/Agamnentzar/ag-psd/assets/1292113/090892e8-9fd6-40ac-8be2-adf782a72542)

**Comment by Agamnentzar** [comment]
add `fill-rule="evenodd"` to the <path> element

**Comment by zhyyangyang** [comment]
> add `fill-rule="evenodd"` to the element

get~  thank u so much
