### ISSUE TITLE
Writing text layers example failed

### ISSUE THREAD

**Issue by kenisad5566** [Agamnentzar/ag-psd#141]
Thank you for this awesome project. As i follow the document for Writing text layers example, i get a black png without any text. I would greatly appreciate it if you could point out more details.

evn:
node: v16.20.0

code:
```
import { writePsdBuffer ,writePsd, readPsd} from 'ag-psd';
import 'ag-psd/initialize-canvas.js'; // only needed for writing image data and thumbnails
import * as fs from 'fs';
import FileSaver  from 'file-saver';


const file = "demo.psd"
const psd = {
    width: 200,
    height: 200,
    children: [
      {
        name: 'text layer',
        text: {
          text: 'Hello world', // text you want to draw
          transform: [1, 0, 0, 1, 50, 50], // move text 50px horizontally and 50px vertically
          style: {
            font: { name: 'ArialMT' }, // need to provide full name here
            fontSize: 30,
            fillColor: { r: 255, g: 0, b: 0 }, // opaque red
          },
        },
      }, 
    ],
  };
  
const buffer = writePsdBuffer(psd, { invalidateTextLayers : true });
fs.writeFileSync(file, buffer);
const psd2 = readPsd(fs.readFileSync(file));
console.log(psd2);
fs.writeFileSync(file + '.png', (psd2.canvas).toBuffer());
```

This code will get a png just with out text 'Hello world'， only black background.

**Comment by Agamnentzar** [comment]
This library does not render the layers for you, it can only read or write the document, you need to set the canvas of the layer and of the psd document object in order for those canvases to be available after reading the document again. You can read more about it here: https://github.com/Agamnentzar/ag-psd#modifying-documents

If you just want to render some text then this library is completely unnecessary, just use [node-canvas](https://github.com/Automattic/node-canvas) to draw some text onto a canvas and save it as PNG.

**Comment by kenisad5566** [comment]
Thanks. Is there any other psd library can edit psd file text and export as png?

**Comment by Agamnentzar** [comment]
@kenisad5566 I didn't see any that could do that. It would require reimplementing entire photoshop rendering engine.

**Comment by kenisad5566** [comment]
Thanks.
