### ISSUE TITLE
Text Color parsing error in file that was converted from CMYK to RGB

### ISSUE THREAD

**Issue by bhorsting** [Agamnentzar/ag-psd#145]
Hi,

For the attached file, the text in the layer called Adrian is parsed as blue instead of the orange it shows in Photoshop.
This file was converted from CMYK to RGB. I think the text colour values are still described in CMYK; when debugging decodeColor in text.ts I see a color type 2 come in with 5 values. So apparently Photoshop can convert a file to RGB yet not update font colours?

[HSO002-SQ.psd.zip](https://github.com/Agamnentzar/ag-psd/files/11948861/HSO002-SQ.psd.zip)

Text in Photoshop:

![image](https://github.com/Agamnentzar/ag-psd/assets/312809/2e69a2ba-a8ba-4c34-9295-4e90c7e75e0d)

Text as parsed by ag-psd:

<img width="240" alt="image" src="https://github.com/Agamnentzar/ag-psd/assets/312809/bbea446e-f963-40f2-aff3-860c845973e9">

**Comment by Agamnentzar** [comment]
Added support for different color modes in text layer colors in version `16.0.0` Unfortunately you do get CMYK color in there instead of RGB

**Comment by bhorsting** [comment]
Thanks so much!
