### ISSUE TITLE
how to export svg with ( image, path, text as a element of svg ). is there any default function to export SVG.

### ISSUE THREAD

**Issue by aticzz** [Agamnentzar/ag-psd#151]
Image layer instead of image Element of SVG and vector layer instead of path d and text like this.

![git](https://github.com/Agamnentzar/ag-psd/assets/83505478/af0a6b0e-ad54-4449-8a47-04f83cf7de4f)

**Comment by Agamnentzar** [comment]
There's no default way built-in way to export PSD to SVG, but you can get some pointer from other people who tried it: https://github.com/Agamnentzar/ag-psd/issues?q=is%3Aissue+svg

**Comment by aticzz** [comment]
ok thank you for replying
