### ISSUE TITLE
Invalid signature: '8BI' at 0x0 for the attached PSD

### ISSUE THREAD

**Issue by bhorsting** [Agamnentzar/ag-psd#155]
Hi!
I'm trying to open the attached file but I run into an invalid signature error. Not sure why?
Best,
Bas
[warhol.psd.zip](https://github.com/Agamnentzar/ag-psd/files/12727358/warhol.psd.zip)

**Comment by Agamnentzar** [comment]
Published version `17.0.5` with fixes. The issue was incorrect reading of externally linked files, in your case the file is external and there is no data included in the PSD file, so you were getting some random data there.
