### ISSUE TITLE
writeEffects not implemented

### ISSUE THREAD

**Issue by colshacol** [Agamnentzar/ag-psd#16]
Given the code:

```js
import 'ag-psd/initialize-canvas'

import * as fs from 'fs'
import { readPsd, writePsdBuffer } from 'ag-psd'

const buffer = fs.readFileSync(TEMPLATE_PATH)
const psd = readPsd(buffer)

const buffer = writePsdBuffer(psd);
fs.writeFileSync('output.psd', buffer);
```

I am running into this error thrown within `writeEffects`:

```js
function writeEffects(_writer, _effects) {
    throw new Error('Not implemented');
}
```

Can you help me better understand what "effects" is referring to and if there is a way to get around this not being implemented yet?

Furthermore; I will dig in to this and if I haven't found a workaround, I may dive in and attempt a PR.

**Comment by Agamnentzar** [comment]
Those are layer "blending options", mainly dropShadow, innerShadow, outerGlow, innerGlow, bevel, solidFill. It seems I just didn't get to finishing writing for it. I can add it, just need to create some tests and finish the code.

**Comment by colshacol** [comment]
Right on. I apologize, I've been away from Photoshop so long I forgot about the blending options.

I currently have solved this by just rasterizing all the layers styles in Photoshop. Now that I am past that, I have it saving the PSD file, but when I open it in Photoshop all of the text layers have be come static image layers. Know anything pertaining to this?

I appreciate this tool, friend! It is helping me progress on a project started a year ago.

**Comment by Agamnentzar** [comment]
The library should be able to read and write layer affects as of 9d3c5d14e1643d6cbe06e9819fe82931b63a39b3 (v7.0.0) 

You have to keep in mind that the layers store the image data without blending options applied, so if you need to read layer image data with blending options applied you'd have to rasterize them in Photoshop anyway.

The text layers are still not supported by the library, sorry.

**Comment by colshacol** [comment]
> The library should be able to read and write layer affects as of [9d3c5d1](https://github.com/Agamnentzar/ag-psd/commit/9d3c5d14e1643d6cbe06e9819fe82931b63a39b3) (v7.0.0)
> 
> You have to keep in mind that the layers store the image data without blending options applied, so if you need to read layer image data with blending options applied you'd have to rasterize them in Photoshop anyway.
> 
> The text layers are still not supported by the library, sorry.

Don't apologize for what you haven't provided, when you have provided more than you were ever required to. 👍 🙏

**Comment by Agamnentzar** [comment]
Reading text layers is only very basic, and writing is not implemented at all. I'm still working on implementing writing text layer properties.

**Comment by Agamnentzar** [comment]
You can watch https://github.com/Agamnentzar/ag-psd/issues/7 for any progress

**Comment by colshacol** [comment]
Ah, I see. I thought I should be able to change the text and still get the change reflected in the PSD, just it would be rasterized into image form rather than text. My mistake!
