### ISSUE TITLE
Automating the Saving Process for Modified PSD Files

### ISSUE THREAD

**Issue by kknono** [Agamnentzar/ag-psd#160]
Hi,
    After modifying some text in a PSD file, I save it as a new PSD file. However, it must be opened in Photoshop to be correctly saved. Is there a way to automate this saving process?

**Comment by Agamnentzar** [comment]
I think you can just update the canvas and not set `invalidateTextLayers` to true in order to not have to open the file in Photoshop. Unfortunately you'll have to figure out how to draw the text correctly.
