### ISSUE TITLE
How to set the contextual alternates of text style

### ISSUE THREAD

**Issue by mstkmys** [Agamnentzar/ag-psd#162]
I want to set the contextual alternates to true.
I read [TextStyle](https://github.com/Agamnentzar/ag-psd/blob/34eeb4ffb6e2051ba472af551e1c7459a95b573c/src/psd.ts#L331) in [psd.ts](https://github.com/Agamnentzar/ag-psd/blob/master/src/psd.ts), But that property does not appear to exist.

Can you help me?

![ss](https://github.com/Agamnentzar/ag-psd/assets/12792235/2f5e3f0a-50d7-487b-b30c-9d64aca368a8)

**Comment by Agamnentzar** [comment]
Unfortunately it seems that this option is in the extra text data section in PSD document that I didn't manage to decode and there's no documentation for it to my knowledge.

**Comment by mstkmys** [comment]
I see...
Thanks for answer.

Thanks for your development!
