### ISSUE TITLE
shape fill always with color

### ISSUE THREAD

**Issue by harelmotro** [Agamnentzar/ag-psd#166]
Hi,
When creating a shape layer in photoshop that has no color as fill (transparent shape that may still have a stroke), I still get vectorFill with a rgb color from readPsd function. I can't find any indication in the layer object that it has no fill color.

**Comment by Agamnentzar** [comment]
`vectorStroke.fillEnabled` is the field you're looking for, I know it's weird for fill indicator to be in stroke, but that's just how PSD file is structured XD
