### ISSUE TITLE
zlib issue on 20.x.x version

### ISSUE THREAD

**Issue by nfts2me** [Agamnentzar/ag-psd#176]
When updating to 20.x.x from 19.x.x I'm getting this error when doing 'npm install':
```
npm error code 127
npm error path project/node_modules/zlib
npm error command failed
npm error command sh -c node-waf clean || true; node-waf configure build
npm error sh: node-waf: command not found
npm error sh: node-waf: command not found
```

zlib is already part of npm, but it seems that it tries to load it as a module.

**Comment by Agamnentzar** [comment]
Published version `20.1.1` without `zlib`, replaced it with `pako` which shouldn't have these issues.
