### ISSUE TITLE
psd2.children[0].canvas.getBuffer is not a function

### ISSUE THREAD

**Issue by binh27112004** [Agamnentzar/ag-psd#18]
I use ag-psd in nodejs to edit an psd file but when I run example in docs I have this error: 
![image](https://user-images.githubusercontent.com/46067234/77844156-2e2b1b00-71ce-11ea-9ffb-53e20cfde6f8.png).
My code:
`const fs = require('fs');

require('ag-psd/initialize-canvas');

const {writePsdBuffer,readPsd} = require('ag-psd');
const buffer = fs.readFileSync('my-file.psd');
const psd2 = readPsd(buffer);
console.log(psd2);
fs.writeFileSync('layer-1.png', psd2.children[0].canvas.getBuffer());`

**Comment by Agamnentzar** [comment]
make sure the canvas is not empty, try running
`console.log(psd2.children[0].canvas)` to see if it's empty or there's
something wrong with that property

**Comment by ship-hsu** [comment]
Same question here!
It seens 'ag-psd/initialize-canvas' did not work.
The "canvas" property did not appear correctly.
Maybe there are some bugs with nodejs by using require but not import?

**Comment by Agamnentzar** [comment]
The canvas will be empty if the layer is empty, make sure your document has something drawn on that layer

**Comment by binh27112004** [comment]
The layer already has image but it still shows an error
![image](https://user-images.githubusercontent.com/46067234/77999780-6f9e0080-735d-11ea-831f-3d33c8fc7a73.png)
![image](https://user-images.githubusercontent.com/46067234/77999798-775da500-735d-11ea-9fa9-0b661507f3f5.png)
![image](https://user-images.githubusercontent.com/46067234/77999817-7cbaef80-735d-11ea-9d99-5ef1e1c3ab4d.png)

**Comment by Agamnentzar** [comment]
Oh crap, that's my bad, the function is called `toBuffer()` https://github.com/Automattic/node-canvas#canvastobuffer sorry about that. I'll fix the readme.

**Comment by binh27112004** [comment]
Oh I see thank you very much <3
