### ISSUE TITLE
Where to read text paragraph alignment information?

### ISSUE THREAD

**Issue by ieleg** [Agamnentzar/ag-psd#183]
Currently, there are only three types under **paragraphStyle.justification**: left, center, and right. However, when the alignment is in these four cases, justification is not returned.
![image](https://github.com/Agamnentzar/ag-psd/assets/52823905/57b35834-1562-41a6-8bdb-8b917949592d)

**Comment by Agamnentzar** [comment]
Just fixed handling for justified paragraphs in version `20.2.0`
