### ISSUE TITLE
The value of effects.dropShadow.angle is always 90

### ISSUE THREAD

**Issue by jerryzhangjq** [Agamnentzar/ag-psd#186]
<img width="840" alt="image" src="https://github.com/user-attachments/assets/c2019a87-4a37-4d88-b5fa-fc5e2ab7bff4">

<img width="343" alt="image" src="https://github.com/user-attachments/assets/54cfc301-2431-4d16-9444-acd865db08c2">

useGlobalLight true 
angle always 90

**Comment by Agamnentzar** [comment]
By default it has "Use Global Light" enabled (the checkbox next to the angle)

![image](https://github.com/user-attachments/assets/4acbe81f-dec4-4b08-b3e9-f4b8ae7a849e)

When that's enabled it uses value from `psd.globalAngle` instead of the one from the effect

**Comment by Agamnentzar** [comment]
Btw also just released version `20.2.1` with fix for negative `globalAngle` values, so you might want to update if you're going to use `globalAngle` field

**Comment by jerryzhangjq** [comment]
> Btw also just released version `20.2.1` with fix for negative `globalAngle` values, so you might want to update if you're going to use `globalAngle` field

The problem is solved thank you very much
