### ISSUE TITLE
Layer puppet warp data not parsed

### ISSUE THREAD

**Issue by chenhongtu** [Agamnentzar/ag-psd#189]
ag-psd 20.2.1
[psd file](https://drive.google.com/file/d/1aS33T9yCnFdkQoPxdCPPz1R3jb9T5wo1/view?usp=drive_link)

**Comment by Agamnentzar** [comment]
Published version `20.2.2` with a fix, I'm not sure why there's 2 different IDs for the same filter type, so let me know if it works for you correctly now.

**Comment by chenhongtu** [comment]
@Agamnentzar  thank you for your reply,  This psd can be read, but there are some psds that cannot parse puppet warp.
It seems that filterID is not fixed. I saw another code that filterID is less than or equal to 16777215, and it should be distinguished by Fltr.classID
There is also a suggestion that for unknown filterID, Error will be thrown. Can it be changed to output a warning message so that the parsing of other filterFx will not be interrupted。

**Comment by Agamnentzar** [comment]
I released version `20.2.3` with fixes, I used filterID because some filters don't have classID, but I changed it now to use classID when it's there and only fallback to filterID when there's no classID.

**Comment by chenhongtu** [comment]
@Agamnentzar Thank you very much.
Puppet warp data can be parsed normally.
