### ISSUE TITLE
Merge 2 canvas

### ISSUE THREAD

**Issue by binh27112004** [Agamnentzar/ag-psd#19]
My psd file has 2 layers. After reading psd file I uses node-canvas to change my variable( psd2.children[0].canvas). Then I check psd2.canvas, it doesn't change at all. So how can I merge psd2.children[0].canvas and psd2.children[1].canvas to psd2.canvas.

Sorry About My Bad English :(

**Comment by Agamnentzar** [comment]
You have to change both layer canvas and composite image canvas yourself, the library only provides saving and loading for PSD files.

**Comment by binh27112004** [comment]
okay tks you 👍
