### ISSUE TITLE
The internal smart object does not have a canvas field for the corresponding vector layer.

### ISSUE THREAD

**Issue by xmejsieoke** [Agamnentzar/ag-psd#193]
When I deeply parse the buffer of linkedFiles, one of the shape layers does not return a **canvas** field. My version is 20.2.0.
![image](https://github.com/user-attachments/assets/099e2499-317a-486d-9582-e3562b1bcd4c)
[test.zip](https://github.com/user-attachments/files/16435602/test.zip)

**Comment by Agamnentzar** [comment]
It seems that bitmap data is just not there, I guess whatever version of Photoshop was used to save that file doesn't save bitmap data for vector layers expecting them to be redrawn by Photoshop when the file is being opened. Unfortunately this does mean that if you need that canvas you need to draw it yourself based on vector data.

**Comment by xmejsieoke** [comment]
> It seems that bitmap data is just not there, I guess whatever version of Photoshop was used to save that file doesn't save bitmap data for vector layers expecting them to be redrawn by Photoshop when the file is being opened. Unfortunately this does mean that if you need that canvas you need to draw it yourself based on vector data.

I am currently trying to draw vectors and their strokes correctly, but I notice that the dash intervals are incorrect. Is there a transformation that I am unaware of?
![image](https://github.com/user-attachments/assets/a816996d-7cfb-4f2d-a304-a796499fe6ef)
**photoshop:**
![image](https://github.com/user-attachments/assets/25f81410-1827-42f6-b3f3-806c8f724636)
**render on canvas**
![image](https://github.com/user-attachments/assets/80927e5c-2ee4-4c8c-906d-d6618a23c2f1)

**Comment by Agamnentzar** [comment]
I assume that because it's `units: 'None'` then it has to be relative scale, so you'll have to multiply it by something, maybe lineWidth ?

**Comment by xmejsieoke** [comment]
That seems to be the factor.
