### ISSUE TITLE
A better operation value is needed.

### ISSUE THREAD

**Issue by quangxuagoluan** [Agamnentzar/ag-psd#195]
I'm using Paper.js's CompoundPath to perform Boolean operations, CompoundPath allows for adding subpaths with different winding rules. There are two layers: one is a circle, and the other is text converted to a shape. According to the current structure, it returns a flat array of Bézier points that includes Boolean operation types and winding rules. The expectation is not to set a default operation type of combine for paths belonging to this layer, but rather to set it only for specific paths. For example, the **operation** from 0 to 13 should be null. This way, I can place paths 0 to 13 into one CompoundPath, place the 14th path into another CompoundPath, and then perform operations between them.
![image](https://github.com/user-attachments/assets/a58816d2-08b2-4d6a-9e40-4743c4e7f3d8)
![image](https://github.com/user-attachments/assets/0f305019-458d-4112-b7f6-ecded36ca44a)

Could the logic here be causing the issue? If so, could the -1 value be exposed?

![image](https://github.com/user-attachments/assets/d609f40f-2e57-488e-b5ed-ba4ad893e880)

**Comment by Agamnentzar** [comment]
Just published version `21.0.0` with fixed parsing. It should now have `undefined` value in case where the operation is empty.

**Comment by quangxuagoluan** [comment]
You are so efficient.
![image](https://github.com/user-attachments/assets/d73c6c25-8b91-4e9b-a3dd-f9a7fbe6d24a)
