### ISSUE TITLE
In some cases, vectorOrigination does not return information.

### ISSUE THREAD

**Issue by quangxuagoluan** [Agamnentzar/ag-psd#196]
For example, when creating a polygon, it returns an empty keyDescriptorList. Changing parseUnits to parseUnitsOrNumber here might help avoid this issue.
![image](https://github.com/user-attachments/assets/0fc6c438-715c-4470-b952-b4c2d5513f80)

**Comment by Agamnentzar** [comment]
@quangxuagoluan can you provide PSD file that has this issue ?

**Comment by quangxuagoluan** [comment]
[polygon.zip](https://github.com/user-attachments/files/16621162/polygon.zip)
@Agamnentzar

**Comment by Agamnentzar** [comment]
Released version `21.0.1` with a fix

**Comment by quangxuagoluan** [comment]
👍
