### ISSUE TITLE
Unable to get the active & inactive details of text layers.

### ISSUE THREAD

**Issue by CP241089** [Agamnentzar/ag-psd#197]
I want to know which text layers are active in the PSD file and which are inactive. How I can pick this. I have tried multiple way but unable to achieve to get this details.

**Comment by Agamnentzar** [comment]
If you mean if they're visible check if `layer.hidden` is not `true`.

If you mean selected layer then check `psd.imageResources.layerSelectionIds`, it contains list of selected layer IDs.

**Comment by CP241089** [comment]
I want to get all the visible (checked) text layer details from PSD file, I have written below code but I am getting all the visible (checked) & non visible (unchecked) text layers details.

`const fs = require('fs');
const { readPsd, initializeCanvas } = require('ag-psd');
const { createCanvas } = require('canvas');

initializeCanvas(createCanvas);

const filePath = '../psd_files/24x7_rummy_tournament.psd';

function extractTextLayerProperties(filePath) {
  try {
    const buffer = fs.readFileSync(filePath);
    const psd = readPsd(buffer);

    function extractVisibleTextLayers(layers, isVisible = true) {
      layers.forEach(layer => {
        const layerVisible = isVisible && layer.visible !== false;
        
        if (layer.children && layer.children.length > 0) {
          extractVisibleTextLayers(layer.children, layerVisible);
        } else if (layerVisible && layer.text) {
          console.log(`Layer: ${layer.name}`);
          console.log('Text Properties:', layer.text);

          if (layer.effects) {
            console.log('Layer Effects:');
            console.dir(layer.effects, { depth: null });
          } else {
            console.log('No effects found.');
          }
          console.log('---');
        }
      });
    }

    if (psd.children && psd.children.length > 0) {
      extractVisibleTextLayers(psd.children);
    } else {
      console.log('No layers found in the PSD file.');
    }
  } catch (error) {
    console.error('Error reading PSD file:', error);
  }
}

extractTextLayerProperties(filePath);
`

**Comment by Agamnentzar** [comment]
Can you show me a screenshot of your layer list in photoshop and which of the hidden layers are still showing in your script.

**Comment by CP241089** [comment]
In the given screenshot one layer is checked (visible) and one is unchecked (invisible) in PSD file. I want to get the only visible text layers properties but I am getting both the visible & invisible text layers properties.

<img width="281" alt="Screenshot 2024-08-20 at 12 30 34 PM" src="https://github.com/user-attachments/assets/072840b2-231c-47b9-882e-e801feaf500f">

**Comment by Agamnentzar** [comment]
Can you share PSD file with only these 2 layers, maybe there's something weird going on there.

**Comment by CP241089** [comment]
My bad. I have modified my code as per your first comment and it's working as expected.

Below is the modified code.

```
const fs = require('fs');
const { readPsd, initializeCanvas } = require('ag-psd');
const { createCanvas } = require('canvas');

initializeCanvas(createCanvas);

const filePath = '../psd_files/test.psd';

function extractVisibleTextLayerProperties(filePath) {
  try {
    const buffer = fs.readFileSync(filePath);
    const psd = readPsd(buffer);

    function processLayers(layers) {
      layers.forEach(layer => {
        if (layer.hidden === false && layer.text) {
          console.log(`Layer: ${layer.text.text}`);
          console.dir(layer, { depth: null, colors: true });
        }

        if (layer.children) {
          processLayers(layer.children);
        }
      });
    }

    if (psd.children) {
      processLayers(psd.children);
    } else {
      console.log('No layers found in the PSD file.');
    }
  } catch (error) {
    console.error('Error reading PSD file:', error);
  }
}

extractVisibleTextLayerProperties(filePath);
```

Thanks for your support!!
