### ISSUE TITLE
LayerEffectGradientOverlay supports the angle property but is not in the types psd.ts

### ISSUE THREAD

**Issue by skushagra-rocketium** [Agamnentzar/ag-psd#203]
## Problem
LayerEffectGradientOverlay has a property called `angle` which specifies the angle of the gradient overlay effect. This property is not present in the types file although adding it and giving an angle does reflect on photoshop.

## Fix
Add angle property to the LayerEffectGradientOverlay in `psd.ts`

**Comment by skushagra-rocketium** [comment]
<img width="452" alt="Screenshot 2024-10-21 at 11 55 52" src="https://github.com/user-attachments/assets/597e2633-b462-4cb1-85b8-0311463e4b5e">

**Comment by Agamnentzar** [comment]
published version `21.0.2` with fixed type

**Comment by skushagra-rocketium** [comment]
Great!
