### ISSUE TITLE
Why can the height of a layer be calculated by subtracting the top from the bottom

### ISSUE THREAD

**Issue by zhanghang318** [Agamnentzar/ag-psd#204]
I have a question，Why can the height of a layer be calculated by subtracting the top from the bottom, or the width can be calculated by subtracting the left from the right

**Comment by Agamnentzar** [comment]
`bottom = top + height` so `height = bottom - top` etc

**Comment by zhanghang318** [comment]
get it，It has a different meaning from the top and bottom in CSS，Thank you
