### ISSUE TITLE
Gradient Adjustment Layer not in Adjustment Layers

### ISSUE THREAD

**Issue by skushagra-rocketium** [Agamnentzar/ag-psd#205]
## Problem
I have a transparent layer on which I just want to apply the a linear or radial gradient. I was planing on using Gradient Adjustment Layer which is available on photoshop. In the adjustment layer types however this is not present. I believe this is not supported yet. 

## Solution
Can we implement this? I tried other methods of implementing gradient but did not find any luck! How can I apply a gradient on a separate layer such that the after changing the gradient opacity at some point I can see the layer below it. I was trying to use effects but that is not working out for me.

**Comment by skushagra-rocketium** [comment]
## What I want and I get with Gradient Adjustment Layer
<img width="559" alt="Screenshot 2024-10-22 at 13 41 09" src="https://github.com/user-attachments/assets/c683dcf0-eda1-40dc-a56f-6385b9a010fa">

## What I get with effect overlay
<img width="559" alt="Screenshot 2024-10-22 at 13 45 57" src="https://github.com/user-attachments/assets/06d69f2e-a27e-4508-8b2f-dc7bc8e07fd6">


```
I am not very familiar with photoshop. So if there is any other way can you please tell me about that.
```

**Comment by Agamnentzar** [comment]
At least in older version of Photoshop when you add gradient adjustment layer it actually just creates a layer with gradient fill.
```js

    {
      "top": 0,
      "left": 0,
      "bottom": 0,
      "right": 0,
      "blendMode": "normal",
      "opacity": 1,
      "clipping": false,
      "transparencyProtected": false,
      "hidden": false,
      "mask": {
        "top": 0,
        "left": 0,
        "bottom": 0,
        "right": 0,
        "defaultColor": 255,
        "positionRelativeToLayer": false,
        "disabled": false,
        "fromVectorData": false
      },
      "name": "Gradient Fill 1",
      "vectorFill": {
        "type": "solid",
        "name": "$$$/DefaultGradient/NeutralDensity=Neutral Density",
        "smoothness": 1,
        "colorStops": [
          {
            "color": {
              "r": 0,
              "g": 0,
              "b": 0
            },
            "location": 0,
            "midpoint": 0.5
          },
          {
            "color": {
              "r": 0,
              "g": 0,
              "b": 0
            },
            "location": 1,
            "midpoint": 0.5
          }
        ],
        "opacityStops": [
          {
            "opacity": 0.6,
            "location": 0,
            "midpoint": 0.5
          },
          {
            "opacity": 0,
            "location": 1,
            "midpoint": 0.5
          }
        ],
        "style": "linear",
        "angle": 90
      },
      "nameSource": "cont",
      "id": 4,
      "blendClippendElements": true,
      "blendInteriorElements": false,
      "knockout": false,
      "protected": {
        "transparency": false,
        "composite": false,
        "position": false
      }
    }
```

**Comment by skushagra-rocketium** [comment]
Adding it as a `vectorFill` does work! Thanks
