### ISSUE TITLE
Radial Gradient incorrectly displayed on the PSD output

### ISSUE THREAD

**Issue by skushagra** [Agamnentzar/ag-psd#209]
I am writing a radial gradient on my psd file, but when I see the output in photoshop the opacity stops are off. I tried to debug this using readPSD but while doing that I found that the values in the file are correct.
![Screenshot 2024-11-22 at 12 13 03](https://github.com/user-attachments/assets/49b680c5-6305-4b73-b03b-cfbb6900536a)
In read psd I can see the correct opacity which for stop 2 which is 50, but in Photoshop its value is 100.
<img width="451" alt="Screenshot 2024-11-22 at 12 16 02" src="https://github.com/user-attachments/assets/116efbd9-c36d-47bf-808a-5a0b4c7d0c11">
I want my gradient to look like this
![Screenshot 2024-11-22 at 12 16 29](https://github.com/user-attachments/assets/21b434df-3eeb-4f7a-af4a-86d0b8b57ba3)

but it looks like this
<img width="626" alt="Screenshot 2024-11-22 at 12 16 52" src="https://github.com/user-attachments/assets/0640b427-84ef-4ded-8eba-25f67a82a121">

Any ideas why this might be happening?

**Comment by skushagra** [comment]
@Agamnentzar

**Comment by Agamnentzar** [comment]
I think opacity should be from 0 to 1, not 0 to 100, so 0.5 instead of 50 in your case

**Comment by skushagra** [comment]
Hey @Agamnentzar.

That is correct. It should be from 0 to 1.

Thanks for the help!
