### ISSUE TITLE
Generate image from layer

### ISSUE THREAD

**Issue by qathom** [Agamnentzar/ag-psd#21]
Hello,

First of all, thanks for making ag-psd!
Can we generate an output image from a layer?

In README, I see an example with `canvas` only:

```js
const buffer = fs.readFileSync('my-file.psd');
const psd2 = readPsd(buffer);
fs.writeFileSync('layer-1.png', psd2.children[0].canvas.toBuffer());
```

**Comment by Agamnentzar** [comment]
Every layer in PSD file contains bitmap data of it's contents, that data does not have all layer effects or blending modes applied to it though. You can access it in `canvas` field and save it to a file, like in this example. So the image is not generated but read from the file. If you need to generate image for text/vector layers this library can't do that as it would require replicating entire rendering engine of photoshop.

**Comment by qathom** [comment]
Hello @Agamnentzar,

Thanks for the clear explanation!
