### ISSUE TITLE
Text Layer Style Missing

### ISSUE THREAD

**Issue by MathanM** [Agamnentzar/ag-psd#22]
Hi,

Thanks for creating such a wonderful plugin.

When i fetch text layers from psd, some text layers have missing style object.

{
  top: 213,
  left: 1352,
  bottom: 308,
  right: 1828,
  blendMode: 'normal',
  opacity: 1,
  clipping: false,
  transparencyProtected: false,
  hidden: false,
  name: 'ご利用料金',
  text: {
    transform: [
      1.3157875258074918,
      0,
      0,
      1.316233392838027,
      1584.8046875,
      298.44206040037534
    ],
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    text: 'ご利用料金',
    index: 1,
    gridding: 'none',
    antiAlias: 'strong',
    orientation: 'horizontal',
    warp: {
      style: 'none',
      value: 0,
      perspective: 0,
      perspectiveOther: 0,
      rotate: 'horizontal'
    }
  },
  nameSource: 'rend',
  id: 8,
  blendClippendElements: true,
  blendInteriorElements: false,
  knockout: false,
  protected: { transparency: false, composite: false, position: false },
  layerColor: 'none',
  timestamp: 1588305488.703038,
  referencePoint: { x: 1100.8518677539773, y: -653.8262456683206 },
  canvas: [Canvas 476x95],
}

**Comment by MathanM** [comment]
I have attached the PSD file for testing
[test.psd.zip](https://github.com/Agamnentzar/ag-psd/files/4563909/test.psd.zip)

**Comment by Agamnentzar** [comment]
There was an error in parsing text layer data, it should be fixed in e68367647dc5f98fa8b86a62445def29d9cea4b0
I released new version `11.0.2` with the fix

**Comment by MathanM** [comment]
Thank you for the quick fix.  Awesome support
