### ISSUE TITLE
Font size calculation issue

### ISSUE THREAD

**Issue by MathanM** [Agamnentzar/ag-psd#23]
Some times the font size of the text layer differs from font size in the PSD

{
  top: 443,
  left: 249,
  bottom: 538,
  right: 725,
  blendMode: 'normal',
  opacity: 1,
  clipping: false,
  transparencyProtected: false,
  hidden: false,
  name: 'ご利用料金',
  text: {
    transform: [
      1.3157875258074918,
      0,
      0,
      1.316233392838027,
      481.8046875,
      528.4420604003753
    ],
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    text: 'ご利用料金',
    index: 0,
    gridding: 'none',
    antiAlias: 'strong',
    orientation: 'horizontal',
    warp: {
      style: 'none',
      value: 0,
      perspective: 0,
      perspectiveOther: 0,
      rotate: 'horizontal'
    },
    useFractionalGlyphWidths: true,
    superscriptSize: 0.583,
    superscriptPosition: 0.333,
    subscriptSize: 0.583,
    subscriptPosition: 0.333,
    smallCapSize: 0.7,
    paragraphStyle: {
      justification: 'center',
      autoHyphenate: false,
      autoLeading: 1.75,
      leadingType: 1
    },
    style: {
      font: [Object],
      fontSize: 74.45488,
      leading: 21,
      autoKerning: true,
      kerning: 0,
      ligatures: false,
      styleRunAlignment: 3,
      fillColor: [Object],
      strokeColor: [Object]
    }
  },
  nameSource: 'rend',
  id: 5,
  blendClippendElements: true,
  blendInteriorElements: false,
  knockout: false,
  protected: { transparency: false, composite: false, position: false },
  layerColor: 'none',
  timestamp: 1588358251.103778,
  referencePoint: { x: -2.1481322460226693, y: -423.82624566832055 },
  canvas: [Canvas 476x95]
}

Font size  i am getting is 74.45488, but font size in PSD is 98
But i am getting approximate value if i multiply it with text transform
Text Transform[0] = 1.3157875258074918
74.45488 * 1.3157875258074918  = 97.96 

I have attached Test PSD for your reference
[test.psd.zip](https://github.com/Agamnentzar/ag-psd/files/4565853/test.psd.zip)

**Comment by MathanM** [comment]
I think font size should be multiplied by Text Transform[3] for accurate results

**Comment by Agamnentzar** [comment]
That might be the case, I'm returning the value directly from psd file, the photoshop UI might be multiplying the value to make it easier to users to compare the sizes of different text fields.

If this is the case I don't think anything should be changed, since that's how the PSD file stores the size information.
