### ISSUE TITLE
new text cropping

### ISSUE THREAD

**Issue by jonnymangothinkjam** [Agamnentzar/ag-psd#24]
Hi, 

running into an issue changing text, where the new text layer moves position, and changes font colour and size after a certain point. 

here's the starting point:

![image](https://user-images.githubusercontent.com/25662069/82157435-50115780-9879-11ea-9e29-6d501cbe1e35.png)

here's how it returns:

![image](https://user-images.githubusercontent.com/25662069/82157448-66b7ae80-9879-11ea-8c08-0ebd99f44cf3.png)

here's the code: 

```javascript

const fs = require('fs');
const {
    readPsd, writePsdBuffer, writePsd
} = require('ag-psd');
require('ag-psd/initialize-canvas');
const inputBuffer = fs.readFileSync('read.psd');
const psd = readPsd(inputBuffer);


psd.children[1].text.text = "Goodbyeeeeee"


   const buffer = writePsdBuffer(psd, { invalidateTextLayers: true });
   fs.writeFileSync('TEST.psd', buffer);
```

i tried grabbing the whole object and then changing the text, but the result was the same

```javascript


const fs = require('fs');
const {
    readPsd, writePsdBuffer, writePsd
} = require('ag-psd');
require('ag-psd/initialize-canvas');
const inputBuffer = fs.readFileSync('read.psd');
const psd = readPsd(inputBuffer);






let newData = psd.children[1]
newData.text.text = "Goodbyeeeeee"
psd.children[1] = newData;

   const buffer = writePsdBuffer(psd, { invalidateTextLayers: true });
   fs.writeFileSync('TEST.psd', buffer);
```

**Comment by Agamnentzar** [comment]
Can you send me psd file that has that issue so I can check it ?

**Comment by jonnymangothinkjam** [comment]
thanks for getting back. zip file attached (result and input files)


[Archive.zip](https://github.com/Agamnentzar/ag-psd/files/4640856/Archive.zip)

**Comment by Agamnentzar** [comment]
I has to do with text area, if I put text on the canvas by clicking instead of dragging and create text without text area the it works fine, I'll check if it's possible to handle that but that parameter might be in the obfuscated part of text data so it might be impossible to handle it.

You can try using the method I mentioned with placing text by clicking on the center of the canvas instead of dragging text area.

**Comment by jonnymangothinkjam** [comment]
ah ok, thank you. I see now. 

So it can basically handle point text but not paragraph text. bounding boxes help keep the text from overflowing on larger areas so if it could handle this this would be ace!

i followed advice on setting click text to pargraph text and again the text moved off to the left ( although it did stay the same colour and size)

https://graphicdesign.stackexchange.com/questions/10945/resize-text-bounding-box-in-photoshop

**Comment by Agamnentzar** [comment]
I managed to find the fields responsible for handling box text, it should be handled correctly in version `11.1.0`
