### ISSUE TITLE
PSD write metadata 

### ISSUE THREAD

**Issue by brewmanandi** [Agamnentzar/ag-psd#25]
Hi,

wanted to know if it's possible to write PSD metadata with ag-psd. We are interested in writing "Basic" and "IPTC" metadata. Or would it be possible to load the generated PSD with another package and add the metadata?

Also I noticed ag-psd always writes the PSDs with 72 dpi - any way to change that?

**Comment by Agamnentzar** [comment]
IPTC metadata structure seems really complicated and the documentation is really confusing so I never added it, sorry.

To adjust dpi use `psd.imageResources.resolutionInfo` field, here's example value:
```json
resolutionInfo: {
      horizontalResolution: 72,
      horizontalResolutionUnit: 'PPI',
      widthUnit: 'Centimeters',
      verticalResolution: 72,
      verticalResolutionUnit: 'PPI',
      heightUnit: 'Centimeters'
},
```
