### ISSUE TITLE
Difference with psd.js?

### ISSUE THREAD

**Issue by dpyzo0o** [Agamnentzar/ag-psd#26]
Hi, this library looks very promising. I wonder what is the major difference compared to [psd.js](https://github.com/meltingice/psd.js)? 

e.g, what psd.js cannot do that makes you to create this library? I'm just searching for psd parse libs and want to get more info to make decisions.

Thanks!

**Comment by Agamnentzar** [comment]
I don't think psd.js let's you create PSD files and I really didn't like how complicated the api was there.

**Comment by dpyzo0o** [comment]
> I don't think psd.js let's you create PSD files and I really didn't like how complicated the api was there.

That's true. I also think ag-psd has a much better api at a glance. I will give it a try, thanks!
