### ISSUE TITLE
Invalid effect key

### ISSUE THREAD

**Issue by dpyzo0o** [Agamnentzar/ag-psd#28]
There are some output in the console when I parse some psd files, see below

![Screen Shot 2020-06-03 at 15 06 11](https://user-images.githubusercontent.com/24768249/83606268-e0ef6f00-a5ab-11ea-8d16-97571ffd24f2.png)

It does not break anything, at least all the information I need can be extracted successfully. Is there a way to not show these output(just to keep the console clean)?

**Comment by dpyzo0o** [comment]
I can solve it with `console.log = () => {}` but it feels very hacky, is there any options that I can use to suppress the console output from `ag-psd`?

**Comment by Agamnentzar** [comment]
That was some leftover debug logging, I removed it as of version `11.1.2`

You can send me PSD file that was giving you errors if It's not a problem and I'll add handling for those effect keys.

**Comment by dpyzo0o** [comment]
@Agamnentzar Sorry I cannot send you the psd files due to company regulations. Not a big problem, I can go with the hacky solution at the moment.

**Comment by Agamnentzar** [comment]
That's ok. When you update to `11.1.2` it will stop logging, so you won't have to use the hack.
