### ISSUE TITLE
How can we add Paragraph Text?

### ISSUE THREAD

**Issue by dhaneshwarsingh** [Agamnentzar/ag-psd#29]
Hi,

I am creating a psd file which contains multiple text and image layers. but I am looking for the support of paragraph text instead of pointText. I looked over the documentation but not able to find any such document for paragraph Text. so my question is- How can we add paragraph text inside the Text layer! Please let me know if there is any way to achieve this.

**Comment by simonwilbert** [comment]
I also would like to create paragraph text layers.  Is this easy to do.  WOuld it be easy to do as a fork?

**Comment by Agamnentzar** [comment]
Create PSD file with example of the text layer that you want to achieve and then read the file into JSON or console.log to see how the structure looks like, then you can replicate it yourself. Keep in mind that the library has some limitations when working with text and you need to rely on Photoshop to ask you to redraw the layer when you open the PSD file, like shown here: https://github.com/Agamnentzar/ag-psd#updating-text-layers
