### ISSUE TITLE
Layer left, top, bottom, right, width and height can not be set

### ISSUE THREAD

**Issue by human-a** [Agamnentzar/ag-psd#3]
Hi

First of all thank you very much for this fantastically useful lib.

I have one issue with it though. I got everything to work for me in a layered canvas except for positioning my layers.

I am trying to export my HTML5 canvas (fabricJS) as PSD file and keep all the layers. The problem is that no matter what I set for left, top, bottom, right, width or height, ag-psd is going to modify those numbers, crop the layers etc.

The only numbers that work are ```left: 0, top: 0, right: canvas.width, bottom: canvas.height``` but these are not the positions I want.
Even if I hard code top, left etc. then I use ```writePsd(psdObject)``` it mutates my PSD object and changes the layer positioning. I did dig into the source code, but could not find out why it changes those numbers.

Any help is more than helpful.

**Comment by human-a** [comment]
I tried to put each layer inside its own group and position the group, but the results are still the same.
I noticed you published an update a couple of hours ago, tired that one too, but the results are still the same. Any help would be appreciated.

**Comment by Agamnentzar** [comment]
I checked the code, and it seems that if you define left, top, right, bottom they're used to crop the layer canvas, which is definitely not correct behavior. I'll look into fixing it tomorrow.

**Comment by human-a** [comment]
Thanks. Another problem is that ag-psd does not respect the left, top, etc. that I supply it when writing to psd. The numbers always change.

**Comment by Agamnentzar** [comment]
Yeah, I will fix that issues too

**Comment by Agamnentzar** [comment]
I fixed handling for layer positioning, also changed automatic transparent pixel trimming to an option so it shouldn't change the layer position without your knowledge. Also made sure the passed PSD object is not mutated inside writePsd method.

Let me know if everything is good, and re-open the issue if there are any problems with it.

**Comment by human-a** [comment]
Thanks for the update.

It kinda works.

Here are the problems:

1) It still crops the layers, especially if I calculate the right and bottom wrong.
2) Leaving the right and bottom will end up creating weird results. I dug into the ```helpers.js``` and found the following as the usual suspects:

line 80 to 85

```javascript
    if (typeof layer.right === 'undefined') {
        layer.right = canvas ? canvas.width - layer.top : layer.left;
    }
    if (typeof layer.bottom === 'undefined') {
        layer.bottom = canvas ? canvas.height - layer.left : layer.top;
    }
```
I think there is an issue with how ```layer.right``` and ```layer.bottom``` are being calculated. What will ```width - top``` and ```height - left``` result in? shouldn't it be ```width - left (or right)``` and ```height - top (or bottom)```?

3) No matter what I do, if the right and bottom are not 100% accurately calculated by me, it would end up regenerating the same right and bottom, possibly caused by lines 100 and 101.
```javascript
    layer.right = layer.left + layerWidth;
    layer.bottom = layer.top + layerHeight;
```
This could will reset the bottom and right values, not matter what I eneter in my code. I tried to make these two lines conditional but if I touch it the PSD file will not open and it shows the following error in photoshop: "**Could not complete your request because an unexpected end-of-file was encountered.**"

The last issue, in my case, does not allow me to generate a retina (@2x) version of my PSD, because it regenerates the bottom and right by itself. I could get a working PSD with the correct positioning if I ignore the 2x version, in my case, it is necessry, because ag-psd does not support PSD layer scaling feature.

I think, if there was not any cropping, then the bottom and right options would not be necessary at all, but I may be wrong.

I look forward to hearing your thoughts.

**Comment by Agamnentzar** [comment]
Oops, that's definitely wrong, somehow test cases didn't catch it, I'll look into it

**Comment by Agamnentzar** [comment]
@human-a what would be the expected behavior if the bottom & right does not fit the canvas size. Right now I'd be leaning toward cropping/padding the canvas, since you could just left bottom/right undefined if you wanted to adjust those values instead.

**Comment by Agamnentzar** [comment]
I released a fix for handling layer left/top/right/bottom, if present it will use left/top/right/bottom values and crop/pad given canvas, if not present it will use canvas size to fill-in missing fields

**Comment by human-a** [comment]
**It worked** this time and I could manage to generate the @2x retina version as well.

There are two things still in the ```helpers.js``` file that I think might cause troubles for some:

lines 117 and 118 are re-assigning right and bottom, would it better to write them as so?:

```javascript
if (typeof layer.right === 'undefined') {
    layer.right = layer.left + layerWidth;
}
if (typeof layer.bottom === 'undefined') {
    layer.bottom = layer.top + layerHeight;
}
```

Also, line 105 and 106 are being done after you check for existence of canvas on line 103, so it would be a safer bet to change lines 105-106 to the following:

```javascript
var layerWidth =canvas.width;
var layerHeight = canvas.height;
```

Or maybe there is something missing in the logic behind your code.

-----------------------------------
As of you you question on "expected behavior if the bottom & right does not fit the canvas size" I think if you disable cropping it would be much better, when it comes to PSD files, this kind of cropping of layers is not that useful. If you could somehow enable clip-mask layers, then it would be a much more practical cropping, otherwise, just ignoring the right, bottom and letting the layer be the size of the it's canvas without cropping makes more sense in my opinion.

-----------------------------------
All that said, I want to thank you for this wonderfully great library you have created, it truely is a lifesaver for us.

**Comment by human-a** [comment]
By the way, will there ever be a possibity for you to add support for text and shape layers? Is it even possible and are you willing to add it at some point in future?

**Comment by Agamnentzar** [comment]
I simplified it and changed it so it always keeps the canvas size intact (no cropping or padding)

I started looking into text layer handling, but it's pretty complicated and the documentation is not very good so I'm sure how it will go yet

**Comment by human-a** [comment]
Awesome, it works as expected.

As of text support feature, I understand, I tried to understand it using adobe's docs but it made things even more complicated. Thanks anyways :)
