### ISSUE TITLE
Text stroke properties not working

### ISSUE THREAD

**Issue by dhaneshwarsingh** [Agamnentzar/ag-psd#31]
Hi,

I was trying to add text stroke properties like stroke color, stroke width but that is not working? is there any way to achieve this?

**Comment by Agamnentzar** [comment]
Try making document with text stroke and then read it and see how the structure looks like for what you want to achieve. Also make sure you're aware of the limitations with text layers mentioned here: https://github.com/Agamnentzar/ag-psd#updating-text-layers
