### ISSUE TITLE
invalid font-size for text block

### ISSUE THREAD

**Issue by zababurinsv** [Agamnentzar/ag-psd#33]
Hi.

i have psd file and parse with ag-psd

`obj['PSD']['psd'] = PSD.readPsd(p, { skipLayerImageData: false, skipCompositeImageData: false, skipThumbnail: true });`

And create html file. But two text cells have the wrong font size.

![image](https://user-images.githubusercontent.com/22741813/95028080-5d9f7080-06a6-11eb-8375-63531bc9f5e8.png)

it is ORG and erase.

Tell me please it is error in ag-psd module or it is in psd file ?

in psd file css mode font-size is true.

![image](https://user-images.githubusercontent.com/22741813/95028131-bcfd8080-06a6-11eb-9e62-d1b2ecfc36a6.png)

**Comment by Agamnentzar** [comment]
The value you get in UI is font size multiplied by text transform, so make sure the transform is not scaling it up or just multiply the size by transform

**Comment by zababurinsv** [comment]
How i can 

![image](https://user-images.githubusercontent.com/22741813/95028845-17e5a680-06ac-11eb-9c78-76769c1bb484.png)

In my console, the values and the object are displayed after the file is converted by the library. In the field, the font size is the number 125. How can I convert it to get 54?

**Comment by Agamnentzar** [comment]
there should be `transform` property on `text` object

**Comment by zababurinsv** [comment]
Yes Here he is

How can I choose one of the six values?

![image](https://user-images.githubusercontent.com/22741813/95028934-e6b9a600-06ac-11eb-8336-81166215489c.png)

**Comment by Agamnentzar** [comment]
`transform[0]` is x scale and `transform[4]` is y scale, you can multiply be either of them if they're the same, or average of the two

**Comment by zababurinsv** [comment]
I didn't know that. Correct values are obtained.

Thanks very much !

**Comment by zababurinsv** [comment]
What do the other values mean?

**Comment by Agamnentzar** [comment]
it's regular 2d transform matrix, usually 0 and 3 are x & y scale and 4 & 5 are x & y position, but if 1 & 2 are not 0 there's also rotation/skew involved, you can directly apply it in CSS by using `transform: matrix( ... );` CSS property

**Comment by zababurinsv** [comment]
Thanks. I will read
