### ISSUE TITLE
ag-psd taking very much memory while reading large files like 170MB

### ISSUE THREAD

**Issue by gofurnazarov** [Agamnentzar/ag-psd#39]
ag-psd taking about 2GB ram when reading 170MB PSD file in browser.  Is there any workaround to reduce ram usage? I only need images of the PSD file.

**Comment by Agamnentzar** [comment]
The image data in PSD file is compressed, so it will take more to hold decompressed image data, depending on how many layers you have and how well the compressed 170MB seems like it's a lot.

If you only need composite image data for the whole document, use these options: `{ skipLayerImageData: true, skipThumbnail: true }`

If you need layer image data, use these options: `{ skipCompositeImageData: true, skipThumbnail: true }` (although this one will not save that much memory)

You can calculate how much memory it should theoretically take by using this calculation: `number_of_layers * document_width * document_height * 4` bytes and check if 2GB is close to that or if it's a lot more than it should.

**Comment by Gofurjon** [comment]
Thank you for quick reply
