### ISSUE TITLE
Smart object support

### ISSUE THREAD

**Issue by radakuceruSM** [Agamnentzar/ag-psd#40]
Is there any plan to add smart object support? Or do you have any hack for this?

**Comment by Agamnentzar** [comment]
I'm looking into adding it

**Comment by Agamnentzar** [comment]
I added basic support for smart objects in version `11.2.0` look for `linkedFiles` field on the document and `placedLayer` field on the layers.

Let me know if you encounter any issues with it.

**Comment by radakuceruSM** [comment]
Great! Thanks for your help and fast response!
