### ISSUE TITLE
Deselect all layers

### ISSUE THREAD

**Issue by konri** [Agamnentzar/ag-psd#41]
Hi, 
First of all great tool!
I have a case that I need to generate PSD and I've done successfully with your library, but I need to deselect all layers/create PSD without any selection. Right now when I open generated psd file I see that by default first layer is selected. 
Is possible to create PSD without any selected layer? 
Thanks

**Comment by Agamnentzar** [comment]
Selected layers are not being saved in the PSD file. Photoshop will just select first layer, by default, when you open  a document.

**Comment by konri** [comment]
Thanks for the answer!

**Comment by Agamnentzar** [comment]
Correction: list of selected layers is accessible at `psd.imageResources.layerSelectionIds`
