### ISSUE TITLE
Fill overlay blend mode read value is wrong when it is color burn

### ISSUE THREAD

**Issue by sasensi** [Agamnentzar/ag-psd#45]
When the fill overlay blend mode value is set to `color burn`, it is returned as `normal` in the parsed file.
Here is a file reproducing the issue when parsed: [fill-overlay-color-burn.zip](https://github.com/Agamnentzar/ag-psd/files/5927657/fill-overlay-color-burn.zip)

![Capture d’écran 2021-02-04 190639](https://user-images.githubusercontent.com/11247504/106935818-20162700-671c-11eb-8ec1-2b317c52b1e6.png)

![Capture d’écran 2021-02-04 190808](https://user-images.githubusercontent.com/11247504/106935994-53f14c80-671c-11eb-96a3-daccc1f2e90e.png)

I tested many other blend modes which are returned as expected and the `color burn` blend mode is also accepted when writing file.

**Comment by Agamnentzar** [comment]
You're looking at the wrong layer, the one in the screenshot is the one with red Color Overlay, hence the color:
```json
"color": {
    "r": 255,
    "g": 0,
    "b": 0
}
```

**Comment by sasensi** [comment]
Oops, you're right, sorry about that.
Thanks for the quick answer.
