### ISSUE TITLE
Does library support layer mask and gradient?

### ISSUE THREAD

**Issue by dhaneshwarsingh** [Agamnentzar/ag-psd#46]
Hi,

Does library support layer mask and gradient? basically we wanted to achieve reflection effect, we tried reading the psd files containing layer mask and gradient but these properties does not found. if that does not support then is there any plan to add these functionality?

**Comment by Agamnentzar** [comment]
Can you send me an example PSD with those fields ? I think the mask should already be supported is `mask` field but the gradient is not, I'll look into it.

**Comment by Agamnentzar** [comment]
I fixed some issues with reading and writing gradients and released ads version `11.4.2`, you can see example of gradient data here: https://github.com/Agamnentzar/ag-psd/tree/master/test/read/gradient

**Comment by dhaneshwarsingh** [comment]
Hi, 

Thanks for your prompt response, I really appreciate it. I checked with the updated version but still gradient data is not there however mask properties are there. The example PSD and the JSON output has been attached.
[reflection_efect_data.zip](https://github.com/Agamnentzar/ag-psd/files/5936250/reflection_efect_data.zip)

**Comment by Agamnentzar** [comment]
It seems that gradient is being converted to bitmap when you make it a mask in this case, unless I'm missing something. There doesn't seem to be any gradient data in the file and there's no way to edit the gradient in Photoshop.
