### ISSUE TITLE
Gradient scale is lost when writing

### ISSUE THREAD

**Issue by sasensi** [Agamnentzar/ag-psd#48]
If you read this file: [gradient-scale.zip](https://github.com/Agamnentzar/ag-psd/files/5951920/gradient-scale.zip), you get the scale value as expected.
![Capture d’écran 2021-02-09 152227](https://user-images.githubusercontent.com/11247504/107376834-a2229900-6aea-11eb-9fb6-6e2aac512f2a.png)
But if you try to write the content to a new file, the scale value is lost.

Before:
![Capture d’écran 2021-02-09 151909](https://user-images.githubusercontent.com/11247504/107376947-bebed100-6aea-11eb-85c7-8c8a166d32c0.png)
After:
![Capture d’écran 2021-02-09 151918](https://user-images.githubusercontent.com/11247504/107376960-c1b9c180-6aea-11eb-9844-fb0fcd992492.png)

The scale value is settable using the UI in the following panel:
![Untitled-1](https://user-images.githubusercontent.com/11247504/107377345-25dc8580-6aeb-11eb-89e3-8a6199931f62.png)

**Comment by Agamnentzar** [comment]
It seems to work fine for me, are you using latest version? an issue with gradient scale was fixed in a recent version.

**Comment by sasensi** [comment]
Oh, you're right, I missed the latest version, this is indeed already fixed !
Sorry again for the false alarm and thank you for the quick answer and great work 😃
