### ISSUE TITLE
Vector mask boolean operations are not supported

### ISSUE THREAD

**Issue by sasensi** [Agamnentzar/ag-psd#49]
Both following files produce the same output when we read them using the library, while they use a different boolean operation to blend their vector mask shapes:
- [fileA.zip](https://github.com/Agamnentzar/ag-psd/files/5981253/fileA.zip)
- [fileB.zip](https://github.com/Agamnentzar/ag-psd/files/5981255/fileB.zip)

Here's how to set this setting from the UI:
![Capture d’écran 2021-02-15 122540](https://user-images.githubusercontent.com/11247504/107941082-78092500-6f89-11eb-85ff-f08f37b526ae.png)

**Comment by Agamnentzar** [comment]
I release a fix for the problem in version `11.5.1`, you should see `operation` field on all vector paths now.

Let me know if you still encounter any issues.

**Comment by sasensi** [comment]
Awesome, this seems to work like a charm !
Thank you for the reactivity 👍
