### ISSUE TITLE
When indexing fillColor, color properties do not exist?

### ISSUE THREAD

**Issue by Nickuhhh** [Agamnentzar/ag-psd#50]
![image](https://user-images.githubusercontent.com/25470747/108117003-60ee3400-706a-11eb-891f-9500e98be6ad.png)
The weird thing about this is if I go into the source and change the `Color` type to
```ts
export declare type Color = RGBA | RGB | HSB;
```
it will say that FillColor.b exists since all other types (RGBA & RGB) both share that property.
Now if I were to just change it to `RGBA | RGB` since they share `r`, `g`. & `b`,  it says that those are the only properties that exist, although it should also let me index `a`, but again... it says that it doesn't exist.

**Comment by Agamnentzar** [comment]
You need to find out which type it actually is by using something like this:
```ts
if ('a' in fillColor) {
  // color is RGBA
  console.log(fillColor.r, fillColor.g, fillColor.b, fillColor.a);
} else if ('r' in fillColor) {
  // color is RGB
  // and so on
}
```

**Comment by Nickuhhh** [comment]
Ok, thanks. IMO, this feels kinda dirty and it should be handled better.

**Comment by Agamnentzar** [comment]
This is just how union types work in typescript, depending on what you need to do you can hide that complexity under some helper method, or if you're only working with some limited number of files you can just assume you're always get RGB and just cast it with `fillColor as RGBA`.
