### ISSUE TITLE
toBuffer doesn't exist of canvas.

### ISSUE THREAD

**Issue by Nickuhhh** [Agamnentzar/ag-psd#51]
![image](https://user-images.githubusercontent.com/25470747/108126347-bed54880-7077-11eb-99cd-251e185850f8.png)
I'm trying to export a canvas to a png and it says to use method `toBuffer`, but it doesn't exist?

**Comment by Agamnentzar** [comment]
Are you using it in nodejs or browser ?

In browser canvas doesn't have `toBuffer` method, you can use either `toBlob` or `toDataURL`

If you're running it in nodejs be sure to install node-canvas and bootstrap it like this: `import 'ag-psd/initialize-canvas';`

**Comment by Nickuhhh** [comment]
I'm using nodejs and it runs correctly, except it's linting incorrectly. Maybe I have something set up wrong in my package? Would you know how to fix it?

**Comment by Agamnentzar** [comment]
Oh wait you mean typescript is not compiling. Yeah, by default it assumes canvas are browser canvas objects so the method will not be there. You can patch it by adding your own typings file with something like this: 
```ts
interface HTMLCanvasElement {
	toBuffer(mimeType?: string, options?: { compressionLevel?: number; filters?: number; }): Buffer;
}
```
to extend default HTMLCanvasElement with this method.

Or you can just cast to `Canvas` type from node-canvas, or just `any` if you don't mind it being a bit hacky.
