### ISSUE TITLE
Exporting to png w/ effects

### ISSUE THREAD

**Issue by Nickuhhh** [Agamnentzar/ag-psd#52]
I'm trying to export each layer as a png using this method
![image](https://user-images.githubusercontent.com/25470747/108141067-06b49980-7091-11eb-9fc2-238f8668d5c1.png)
I was wondering if it's possible to preserve any layer effects, such as a color overlay?
Is it also possible to merge any clipping/vector masks when exporting the png?
And finally, is it possible to preserve group effects?

**Comment by Agamnentzar** [comment]
No, all of those are generated by photoshop at runtime and would require duplicating whole photoshop rendering engine to replicate them in this library.

The only image with all of the effects applied is the composite image for the whole file, available in `psd2.canvas`

**Comment by Nickuhhh** [comment]
Do you know of any javascript/typescript libraries that are capable of exporting as png, with effects? Maybe even one that requires you to open photoshop? Or maybe one that rasterizes all layers with effects/masks automatically?

**Comment by Agamnentzar** [comment]
I haven't seen any npm libraries that would do anything like that. I think you might need to look into Photoshop scripting (I think they do some support some version of nodejs inside Photoshop now) depending on what exactly you need to do.

Probably a script that hides all layers and then shows layers one by one and exports to PNG would do what you want, but I'm not familiar with Photoshop scripting.

**Comment by nkihrk** [comment]
Hi,
I think it is not the appropriate solution you are looking for, but I recently created some repository called SeekPSD which can render each layer of the PSD. I use ag-psd for parser. I's not like a library, so I'm afraid it won't help you. But I think you can still create your own rendering engine like mine.

This is my project 
https://github.com/nkihrk/seek-psd-archived

This is where it render all layers
https://github.com/nkihrk/seek-psd-archived/blob/master/src/app/service/core/gpu.service.ts

**Comment by Nickuhhh** [comment]
@nkihrk Wow thanks, that's really interesting. I'll check it out, but it does sound like a really cool potential library. I'm still relatively new to ts/js which is unfortunate because I'd definitely make it myself.
