### ISSUE TITLE
Text change not reflected in output canvas

### ISSUE THREAD

**Issue by matthewtoast** [Agamnentzar/ag-psd#53]
Thank you for the great library!

I'm trying to make programmatic edits to text in a .psd file, and then write the updated document to a .png file, without ever needing a human to open Photoshop.

This is my code:

```
const bufferIn = fs.readFileSync('input.psd');
const psdIn = readPsd(bufferIn);
// console.log(psdIn.children[4].children[0].text.text); // => "Lorem ipsum"
psdIn.children[4].children[0].text.text = "TEST";
psdIn.children[4].children[0].canvas = undefined;
const bufferOut = writePsd(psdIn, {invalidateTextLayers: true});
const psdOut = readPsd(bufferOut);
fs.writeFileSync('output.png', (psdOut.canvas as any).toBuffer());
```

When I run this code, `output.png` still has the original content ("Lorem ipsum" instead of "TEST").

Sorry if this is noise—I've read the docs and I'm not 100% clear whether what I'm trying to do is possible or not. Is it?

**Comment by Agamnentzar** [comment]
The library doesn't render the layers, you need to provide your own updated bitmap or update it by opening the document in Photoshop. Implementing that would require us to re-implement whole photoshop rendering engine.
