### ISSUE TITLE
Missing font prevent the text layers update popup from appearing

### ISSUE THREAD

**Issue by sasensi** [Agamnentzar/ag-psd#55]
As mentioned in the documentation, when creating a file from scratch, in order for text layers to be displayed properly, we need to update text layers data when opening the file.

> When you add text layer to PSD file it is missing image data and additional text engine information. When you open file created this way in Photoshop it will display this error message, prompting you to update layer image data. You should choose "Update" which will force Photoshop to redraw text layers from text data. Clicking "No" will result in text layers being left in broken state.

This works perfectly fine for common case but I just discovered that if you open a file that has missing fonts, Photoshop displays a popup dedicated to replacing the missing fonts instead ([file-with-2-fonts.zip](https://github.com/Agamnentzar/ag-psd/files/6139841/file-with-2-fonts.zip)).

![Capture d’écran 2021-03-15 091915](https://user-images.githubusercontent.com/11247504/111123475-aa4d7880-856f-11eb-8c47-7e7d88689fbb.png)
And whatever you do (cancel or replace), you never get the chance to update text layers data.

I also discovered than we can trigger text layers update from the menu:
![Capture d’écran 2021-03-15 092116](https://user-images.githubusercontent.com/11247504/111123604-d9fc8080-856f-11eb-9d8a-1fed428a78e4.png)
So we have a possible manual workaround for this case even it is not ideal.

So my question is, could you, by any chance, do something that would either make the text layers update popup still appear or trigger the update in another way ?

Thank you in advance.

**Comment by Agamnentzar** [comment]
It seems it's a bug introduced in newer versions of Photoshop, my old version handles this case correctly.

![image](https://user-images.githubusercontent.com/572298/111238285-12936d00-85f7-11eb-83a6-56a7f8950c38.png)

I don't see any way to fix this in PSD file itself. Right now I'm just deleting some metadata to force Photoshop to update the layers, there's no designed way to inform Photoshop that it needs to update the layers in PSD file.

**Comment by sasensi** [comment]
Ok, no problem, thank you anyway for looking into it.

**Comment by KawishAli6578** [comment]
@Agamnentzar Can text layers in Photoshop be updated automatically instead of the manual process mentioned in the Updating Text Layers documentation?
thanks
![image](https://github.com/Agamnentzar/ag-psd/assets/95257675/7f4e3e1d-8224-4825-9744-3351bb0cd9b7)

**Comment by Agamnentzar** [comment]
@KawishAli6578 I tried few different things and nothing seems to work, I wasn't able to force photoshop to update it automatically.

**Comment by KawishAli6578** [comment]
@Agamnentzar is their any other library I can use to update text in psd file or any other way .
I do not want to open it in photoshop, I am converting it into PNG file and I will use that PNG file further, but the issue I am facing is after modifying text I am converting the PSD file into PNG, but even in PNG file it does not reflect any change but to reflect changes I need to update it in photoshop

**Comment by Agamnentzar** [comment]
You can't use this library that way, it doesn't do re-rendering for you, you'd have to re-render the layer yourself, and that's hard for text layers. A simpler solution would be to use something like node-canvas directly to render your image.
