### ISSUE TITLE
Difficulties with smart objects

### ISSUE THREAD

**Issue by sasensi** [Agamnentzar/ag-psd#57]
I'm trying to include smart object in my Photoshop file created from scratch with the help of your library.
In order to do it, I tried following the test case for writing smart object that is present in your test suite: https://github.com/Agamnentzar/ag-psd/tree/master/test/write/smart-object

I discovered that the output is only working as expected if we provide the layers canvases as you're doing it here: https://github.com/Agamnentzar/ag-psd/blob/fddc7bffe90f2b0fa64e32529c81556ee487e6af/src/test/psdWriter.spec.ts#L35

If we skip this step (which is my case since I'm creating the file from scratch), the resulting layer is empty, even if we provide the linked file data, as done here: https://github.com/Agamnentzar/ag-psd/blob/fddc7bffe90f2b0fa64e32529c81556ee487e6af/src/test/psdWriter.spec.ts#L44
And I found no way to trigger an update of the layer from Photoshop UI (I expected to find something similar to the text layers update feature).

Generating the needed canvas would not really be a problem when dealing with linked images, as in your test case, since we can easily generate it by reading the file ; but it becomes one when dealing with other type of linked file. My use case requires me to use smart object to include a Photoshop file in another one as a smart object.
Is there a way to do this with your library somehow ?

Thank you in advance.

**Comment by Agamnentzar** [comment]
I tried some experiments and it seems it's not possible to force Photoshop to update smart object layer by itself, it seems to only do that with vector masks. Photoshop will update the layer data when you start transform or edit the linked image.

If you're linking Photoshop file you can read its composite image using the library and then draw it onto the layer, though it does require the target PSD file to have composite image data in it and may produce slightly different results than Photoshop would.

**Comment by sasensi** [comment]
In my scenario, the linked Photoshop file would be created using the library too (from scratch) so this wouldn't work 😞
Thank you for the answer anyway.
