### ISSUE TITLE
Layer style effect, incomplete reading

### ISSUE THREAD

**Issue by Angel-fund** [Agamnentzar/ag-psd#59]
I tried to add two layers of stroke layer styles to one layer, but only one layer of stroke data can be read，The layer style in ps can be added repeatedly, `lmfx` doesn't seem to handle

**Comment by Agamnentzar** [comment]
I added support for multiple blending modes of the same type, released as version `12.0.0`

**Comment by Angel-fund** [comment]
Thank you
