### ISSUE TITLE
Parsing information like distort, warp etc on layers

### ISSUE THREAD

**Issue by hoomanaskari** [Agamnentzar/ag-psd#61]
Hi,

I really love where this library is going. I am still using using a rather older version of the lib, only because I am waiting for 1 specific feature to be added.

I know you have added support for smart objects, but what about information related to distorting, warping etc. of these layers. These could be as simple as before/after coordinates, they can later be fed into a webGL program to edit the warp/distort effect later. The webGL part is of course out of the scope your library, but do you think there is a chance for the mentioned info be parsed for layers?

**Comment by Agamnentzar** [comment]
Do you have example of a file with warped/distorted smart object ?

**Comment by hoomanaskari** [comment]
Yes of course. I have attached a zip file here: [warp.psd.zip](https://github.com/Agamnentzar/ag-psd/files/6432015/warp.psd.zip)

Steps to reproduce:

1. Unzip the file and open in PS
2. select any of the smart layers
3. press command/ctrl + T to enable transform tool
4. right click on the object inside the canvas
5. based on the layer name, select one of the warp/perspective/distort effects
6. You can see the (after) coordinates of the those effects once you enable them.
7. If you double click on the layer (in layers panel), you can see the content of it, flat, without any warp or distortion, which could serve as the (before) coordinates

Please let me know if you need more info/examples etc.

**Comment by Agamnentzar** [comment]
It seems everything is read properly, see `warp` field inside `placedLayer` field.

**Comment by hoomanaskari** [comment]
Oh wow! Thanks for letting me know I could not find it previously. I will give it anpther try.

**Comment by hoomanaskari** [comment]
This part works, but I am having trouble finding the content of smart objects. I know there is a linkedFiles array where each item is connected to a smart object via it's id, but all I see inside the linked files is the Uint8Array. I tried to read this via readPsd functions, but I get the `: Invalid PSD file version: 2` which I guess must have something to do with .psb files not being supported?


Is there a chance to have access to the layers (children) inside those smart objects?

**Comment by Agamnentzar** [comment]
I added support for reading and writing PSB files and released as version `12.1.0`

**Comment by hoomanaskari** [comment]
Wonderful. It works like a charm.

**Comment by hoomanaskari** [comment]
I am trying to wrap my head around something here. I am not sure if I have to start a new issue for it (let me know please)

The information for most of the layers is limited to positioning, color, stroke etc.
When it comes to differentiating for example, shapes, I could not find any info that would help me make a difference between a circle and a rounded rectangle. This way the only way for me to import them into a Canvas, is by importing a rasterized image data stored in the library as a canvas.

I was wondering if Photoshop is providing some of these information, such as, corner radius, diameter, shape types (circle, rectangle, polygon etc.) and for the pen tool, info like the path data etc?

**Comment by hoomanaskari** [comment]
I think I found something under **vectorMask**, though it is hard to differentiate what shape it exactly is (maybe possible with some math, to some extent) but I can derive the path data for vector layers coming from PS using the vectorMask object (of present)

**Comment by Agamnentzar** [comment]
I think Photoshop converts all vector object into bezier paths, so you just get generic bezier control points no matter what shape you use.

**Comment by hoomanaskari** [comment]
Thank you very much, that makes sense.

**Comment by hoomanaskari** [comment]
Here is what I found so far. In photoshop if you right click on a vector layer, and choose copy as SVG, it will only give you the vector path data as bezier curves (mainly M C and L commands)

But if you right click on a layer, select export as, and then choose SVG as your format, you will get the correct shapes, for example for circle you get: 
```svg
<circle class="cls-1" cx="96.5" cy="96.5" r="96.5"/>
```
or for a rectangle with (equally) rounded corners you will get:
```svg
<rect class="cls-1" x="1" y="1" width="169" height="169" rx="47" ry="47"/>
```

anything else comes as a path.

Is this data available in file format too?

**Comment by Agamnentzar** [comment]
Can you provide PSD file that does that? I couldn't find any more shape information in my vector files, so it might be something added in newer versions or Photoshop is just guessing the shape based on arrangement of control points.

**Comment by hoomanaskari** [comment]
[shape-exports.psd.zip](https://github.com/Agamnentzar/ag-psd/files/6452142/shape-exports.psd.zip)
Of course, I have attached a file.

If you right click on the layer and select copy SVG it will give you an SVG with path data.
If you right click on the layer and select export as, and then choose SVG as the export format, for the shapes provided in this attached file, it gives you correct shapes for SVG.

For other shapes, the SVG export (or even the copy as SVG) is way better than the path array provided in the `vectorMask` which is problematic with a lot of edge cases to cover.

For example for a polygon using the sSVG export (or copy) you get something as simple as `d="M196 0l195.906 142.342-74.829 230.314H74.923L.094 142.342 196 0z"`

while in my case, using the path array inside the vectorMask, I ended up having this: 

`d="M 291, 561 C 291, 561, 486.906, 703.342, 486.906, 703.342 L 486.906, 703.342 C 486.906, 703.342, 412.077, 933.656, 412.077, 933.656 L 412.077, 933.656 C 412.077, 933.656, 169.923, 933.656, 169.923, 933.656 L 169.923, 933.656 C 169.923, 933.656, 95.094, 703.342, 95.094, 703.342 L 95.094, 703.342 C 95.094, 703.342, 291, 561, 291, 561 Z"`

As you can see, a lot of unnecessary info for a straight polygon.

Perhaps the most bizarre case belongs to Lines. If you draw simple straight line in photoshop, and then use the vectorMask to try to recreate the line a Canvas, you will end up with 2 cubic bezier curves overlapping each other. They look ok, until you decide to edit them (for example in our case, a pen tool)

I am not sure if the SVG data paths are store in the file or is this is something that can be supported in this library, but if it's possible, it will be a very great additional to an already wonderful library.

**Comment by Agamnentzar** [comment]
I checked and there's no information about the shapes, so it's just guessing the node types from the coordinates (like when both control points have the same coordinates as the point itself you can use regular line instead of bezier)

Here are the points of the rectangle layer from your PSD file:
```
[
  {
    linked: true,
    points: [
      540,
      113.00000667572021,
      540,
      113.00000667572021,
      540,
      113.00000667572021
    ]
  },
  {
    linked: true,
    points: [
      938.0000138282776,
      113.00000667572021,
      938.0000138282776,
      113.00000667572021,
      938.0000138282776,
      113.00000667572021
    ]
  },
  {
    linked: true,
    points: [
      938.0000138282776,
      376.0000205039978,
      938.0000138282776,
      376.0000205039978,
      938.0000138282776,
      376.0000205039978
    ]
  },
  {
    linked: true,
    points: [
      540,
      376.0000205039978,
      540,
      376.0000205039978,
      540,
      376.0000205039978
    ]
  }
]
```
you can see that all x & y values are the same within knots, so it can be simplified to regular polygon. Recognizing all possible simplifications is a bit complicated and seems like a lot of work though, you could maybe just generate SVG code and run it through some SVG minifier (like SVGO) and see what you get that way.

**Comment by hoomanaskari** [comment]
Yes that seems to be the only option since the data is being calculated on the fly by PS and not store.

**Comment by hoomanaskari** [comment]
I have been testing warps/perspectives/distorts, and I have found out that the only time I can have `customEnvelopeWarp` coordinates, is when the default warp is set. Any other options, such as 3x3 4x4 5x5 custom, distort and perspective, and any of the preset warps (arc, flag, wave etc.),  they all have customEnvelopeWarp set to `undefined`.

I checked the source code, and it appears that the `parseWarp` function in `additonallinfo.js` runs twice, the second time it runs, it makes the value undefined.

A psd file is also attached for some of the failing examples, but the fact of the matter is that, they all fail except when the default warp is set. The `uOrder` and the `vOrder` are also always set to 4.
[invalid-werps.psd.zip](https://github.com/Agamnentzar/ag-psd/files/6467919/invalid-werps.psd.zip)

**Comment by Agamnentzar** [comment]
Released version `13.0.0` with fixed handling for warps, additionally changed how `meshPoints` are represented, to something more sensible.
```ts
// old representation
interface Warp {
  meshPoints: { type: 'horizontal' | 'vertical'; values: number[]; }[];
}

// new representation
interface Warp {
  meshPoints: { x: number; y: number; }[];
}

**Comment by hoomanaskari** [comment]
Awesome! Will give it a go, and will report back if I found any issues.

**Comment by rofemen** [comment]
Hello, is there a way to transform the image like Photoshop based on the warp data in the warp field, for example: customEnvelopeWarp?

**Comment by Agamnentzar** [comment]
@rofemen There's no functionality for that kind of warp in HTML canvas, you'd have to find and algorithm for it and do it pixel by pixel yourself, of try to find library that does implements it.

**Comment by rofemen** [comment]
> @rofemen There's no functionality for that kind of warp in HTML canvas, you'd have to find and algorithm for it and do it pixel by pixel yourself, of try to find library that does implements it.

I want to restore the deformation of PS based on the parsed deformation data. Do you know the specific algorithm here, or what is the process?

**Comment by Agamnentzar** [comment]
@rofemen I don't know it, you'd probably have to look for warp algorithms that work like the one in Photoshop, don't know how to find one like that.

**Comment by rofemen** [comment]
> @rofemen我不知道，你可能不得不寻找像 Photoshop 中那样工作的扭曲算法，不知道如何找到这样的算法。

I'm just looking for this redrawing algorithm. I want to ask if the deformation data parsed by ag-psd is the complete photoshop deformation data? This will help my follow-up work

**Comment by Agamnentzar** [comment]
ag-psd returns all the data for warp that is in the PSD file. It should be enough to recreate the warp transform if you manage to replicate the algorithm from Photoshop.

**Comment by rofemen** [comment]
> ag-psd 返回 PSD 文件中的所有 warp 数据。如果您设法从 Photoshop 复制算法，重新创建扭曲变换就足够了。

I still have a question about the meaning of some fields in placedLayer, such as placedLayer.transform, placedLayer.warp.uOrder, placedLayer.warp.vOrder, can you explain it? Or is there any documentation that explains these parameters

**Comment by rofemen** [comment]
> ag-psd returns all the data for warp that is in the PSD file. It should be enough to recreate the warp transform if you manage to replicate the algorithm from Photoshop.

I still have a question about the meaning of some fields in placedLayer, such as placedLayer.transform, placedLayer.warp.uOrder, placedLayer.warp.vOrder, can you explain it? Or is there any documentation that explains these parameters

**Comment by Agamnentzar** [comment]
There's no official documentation for these fields, you have to guess what each of them mean. I don't know how exactly  `uOrder` and `vOrder` are for work, but I just searched for it and found that those are parameters for bezier patches https://mathweb.ucsd.edu/~sbuss/MathCG2/OpenGLsoft/GlGeomShapes/explainGlGeomShapes.html (V. Bezier Patches section)

So maybe the transformation is based on a bezier patch.

**Comment by rofemen** [comment]
> There's no official documentation for these fields, you have to guess what each of them mean. I don't know how exactly `uOrder` and `vOrder` are for work, but I just searched for it and found that those are parameters for bezier patches https://mathweb.ucsd.edu/~sbuss/MathCG2/OpenGLsoft/GlGeomShapes/explainGlGeomShapes.html (V. Bezier Patches section)
> 
> So maybe the transformation is based on a bezier patch.

Confirm again, that is, the data in the placedLayer is also the complete ps data, right?

**Comment by Agamnentzar** [comment]
Yes, there's no more data available, that's all there is in the PSD file.

**Comment by rofemen** [comment]
> Yes, there's no more data available, that's all there is in the PSD file.
ok thanks a lot for your answer, i will try to reproduce his morph

**Comment by zzq0324** [comment]
> > @rofemen我不知道，你可能不得不寻找像 Photoshop 中那样工作的扭曲算法，不知道如何找到这样的算法。
> 
> I'm just looking for this redrawing algorithm. I want to ask if the deformation data parsed by ag-psd is the complete photoshop deformation data? This will help my follow-up work

@rofemen Hi, have you found the algorithm to restore the deformation of psd? If you found, please share with me, thank you very much.

**Comment by 10ef** [comment]
> > > @rofemen我不知道，你可能不得不寻找像 Photoshop 中那样工作的扭曲算法，不知道如何找到这样的算法。
> > 
> > 
> > I'm just looking for this redrawing algorithm. I want to ask if the deformation data parsed by ag-psd is the complete photoshop deformation data? This will help my follow-up work我只是在寻找这种重绘算法。我想问一下 ag-psd 解析的变形数据是不是完整的 photoshop 变形数据？这将有助于我的后续工作
> 
> @rofemen Hi, have you found the algorithm to restore the deformation of psd? If you found, please share with me, thank you very much.嗨，你找到恢复 psd 变形的算法了吗？如果您发现了，请与我分享，非常感谢。

![image](https://github.com/user-attachments/assets/c7348e96-6453-4cc5-ac11-a5c8abe6e47d)
I think I have done it. Welcome to contact me. - hi@10ef.me
