### ISSUE TITLE
Parsed PSD hierarchy incorrect

### ISSUE THREAD

**Issue by vujadin** [Agamnentzar/ag-psd#64]
Here's a PSD file and screenshots from Photoshop and output produced by ag-psd. You can see that ag-psd has placed last 8 elements of document in "modals" group (in original PSD they are not children of "modals" group but part of the document root). In Photoshop "modals" group has only 4 child objects but ag-psd puts the rest of the document child objects in the "modal" group so it now has 12 child objects:

![Screenshot_1](https://user-images.githubusercontent.com/4639385/118113669-dd34b100-b3e6-11eb-83b9-5514d15d50e0.png)

![Screenshot_2](https://user-images.githubusercontent.com/4639385/118113682-e291fb80-b3e6-11eb-9f41-d30dd96bb19a.png)

[error_groups.zip](https://github.com/Agamnentzar/ag-psd/files/6471896/error_groups.zip)

**Comment by Agamnentzar** [comment]
Released version `13.0.1` with a fix, it seems the file had some missing data on one of the layer group terminators, but it was easy to add handling for that.

**Comment by vujadin** [comment]
Great, thanks.
