### ISSUE TITLE
A few specific PSB files cause a crash on read

### ISSUE THREAD

**Issue by Pizzacus** [Agamnentzar/ag-psd#66]
Hi! First I wanted to say how thankful I am that you are maintaining this library, it's extremely helpful to me. I do proofreading on PSD files and I use ag-PSD to extract all the text into LibreOffice, that way I can read it quickly and use the spelling and grammar check to find basic mistakes.

I've been able to get it running without any hurdles. It's very easy to work with the output, especially with the TypeScript definitions. You're doing a very good job! Thank you!

----------------------------

Among all the files I've put into it, there are three so far that cause a crash instantly upon being read. It doesn't really bother me because these files are pretty much empty, but I thought it would be good to report it. It looks like it's all coming from the same error, but I'll include each file separately just in case.

[SFX5.psb](https://i.fiery.me/oMejp.psb)

```log
Error: Invalid signature: '____'  at 0x8b76b
    at readAdditionalLayerInfo (.../node_modules/.pnpm/ag-psd@13.0.1/node_modules/ag-psd/dist/psdReader.js:477:15)
    at .../node_modules/.pnpm/ag-psd@13.0.1/node_modules/ag-psd/dist/psdReader.js:222:17
    at readSection (.../node_modules/.pnpm/ag-psd@13.0.1/node_modules/ag-psd/dist/psdReader.js:638:18)
    at Object.readPsd (.../node_modules/.pnpm/ag-psd@13.0.1/node_modules/ag-psd/dist/psdReader.js:202:5)
    at Object.readPsd (.../node_modules/.pnpm/ag-psd@13.0.1/node_modules/ag-psd/dist/index.js:25:24)
```

[シェイプ 1.psb](https://i.fiery.me/pRE7B.psb)

```log
Error: Invalid signature: '____' at 0x5bc1
    at readAdditionalLayerInfo (.../node_modules/.pnpm/ag-psd@13.0.1/node_modules/ag-psd/dist/psdReader.js:477:15)
    at .../node_modules/.pnpm/ag-psd@13.0.1/node_modules/ag-psd/dist/psdReader.js:222:17
    at readSection (.../node_modules/.pnpm/ag-psd@13.0.1/node_modules/ag-psd/dist/psdReader.js:638:18)
    at Object.readPsd (.../node_modules/.pnpm/ag-psd@13.0.1/node_modules/ag-psd/dist/psdReader.js:202:5)
    at Object.readPsd (.../node_modules/.pnpm/ag-psd@13.0.1/node_modules/ag-psd/dist/index.js:25:24)
```

[シェイプ 2.psb](https://i.fiery.me/0olqe.psb)

```log
Error: Invalid signature: '____' at 0x5be1
    at readAdditionalLayerInfo (.../node_modules/.pnpm/ag-psd@13.0.1/node_modules/ag-psd/dist/psdReader.js:477:15)
    at .../node_modules/.pnpm/ag-psd@13.0.1/node_modules/ag-psd/dist/psdReader.js:222:17
    at readSection (.../node_modules/.pnpm/ag-psd@13.0.1/node_modules/ag-psd/dist/psdReader.js:638:18)
    at Object.readPsd (.../node_modules/.pnpm/ag-psd@13.0.1/node_modules/ag-psd/dist/psdReader.js:202:5)
    at Object.readPsd (.../node_modules/.pnpm/ag-psd@13.0.1/node_modules/ag-psd/dist/index.js:25:24)
```

Note that instead of "____" there were some random characters that I can't copy-paste into GitHub. Maybe logging those in hex would make copy-pasting logs easier. Anyway, it doesn't really matter here.

This is the code I'm using for parsing

```ts
const psd = readPsd(buffer, {
	skipLayerImageData: true,
	skipCompositeImageData: true,
	skipThumbnail: true,
});
```

I'm on Node v16.1.0 and using version 13.0.1 of the lib on Linux.

These files were initially linked files embedded into PSD files. I recursively parse all the embedded files to get **all** the text. Unfortunately, I can't tell you which version of Photoshop was used and whether the author did anything peculiar. I got those files as-is and I will (probably) not be able to reach out to the author as this was done a few years ago.

When I open those files in Krita, they appear empty, so maybe that's what's special about them. I don't know why the author would put an empty PSB file as a linked layer. So this isn't a big issue for me, I just try-catch the parser. Don't feel urged to fix it for me...

Thanks!

**Comment by Agamnentzar** [comment]
Should be fixed in version `13.0.2` it was an issue with PSB files that contain other linked PSB files.

The first file is actually not empty, it's a single comic frame, the other two are some black borders.

**Comment by Pizzacus** [comment]
Well, then I guess Krita may also have a problem with these files.

![image](https://user-images.githubusercontent.com/7659613/119191362-cfce9500-ba7e-11eb-911d-7f9f4caec7b3.png)

I hope I didn't accidentally send an explicit file :cold_sweat: some of the content was actually highly suggestive. (But that would be very unlucky I imagine it wasn't the case.)

I can confirm that I get no errors with the new version :+1: Thank you so much!

**Comment by Agamnentzar** [comment]
They probably have the same error in their PSB reading code, since the file breaks its own rules there for some reason.

It was just a face closeup XD

**Comment by Pizzacus** [comment]
It's a great relief to know I didn't accidentally send you manga lewds :pray: 

I was wondering, do you have any idea as to why those are PSB files? Isn't PSB for very large files? Does Photoshop always use PSB for these kinds of layers or is the person doing the typesetting just doing weird things? Do you see any other reason why they would use PSB?

I just found them like that, as linked layers on a PSD file. It seems all the PSDs which I got from this person embed PSB files. I'm really curious as to whether there might be an underlying reason for this or not.

**Comment by Agamnentzar** [comment]
I don't really know, it might have something to do with embedding, I saw someone else had similar case where PSD file had PSB embedded in it, but I'm not sure. Might just be some quirk of Photoshop.

**Comment by Pizzacus** [comment]
I see. Well, thanks for everything, have a nice weekend!
