### ISSUE TITLE
Can not parse text

### ISSUE THREAD

**Issue by ryanlin1986** [Agamnentzar/ag-psd#67]
[test.zip](https://github.com/Agamnentzar/ag-psd/files/6525511/test.zip)

![image](https://user-images.githubusercontent.com/11850439/119208424-b3f5de00-bad4-11eb-89c8-4d297c90acec.png)

As the image you can see, there is not text property in json, but these objects are actually texts.

**Comment by Agamnentzar** [comment]
Should be fixed in `14.0.0`

It was missing handling for a value for text gridding. Do you know, by chance, where to change "text gridding" value in Photoshop ?

**Comment by ryanlin1986** [comment]
Sorry I have no idea how to change the "text gridding", thanks for the fix, really great lib
