### ISSUE TITLE
Incorrect vector path points

### ISSUE THREAD

**Issue by ryanlin1986** [Agamnentzar/ag-psd#69]
[path.zip](https://github.com/Agamnentzar/ag-psd/files/6565594/path.zip)

The points value are correct but in incorrect order,
for example:
knots[0][4\~5] should be actually at position of knots[0][0\~1],
and knots[1][0\~1] should be actually at position of knots[0][2\~3] and knots[1][2\~3] should be actually at position of knots[0][4\~5],
knots[1][4\~5] should be actually at position of knots[1][0\~1]
![image](https://user-images.githubusercontent.com/11850439/120090063-31070000-c132-11eb-8614-8cb2726c7433.png)

This is what I observed by exporting the layer to svg from photoshop and compared the exported svg points to points in json.
I don't know if this is by design( am I have to manually shift 2 points forward?) or a psd parse bug.

**Comment by Agamnentzar** [comment]
Photoshop doesn't keep the path data in SVG format, it has it's own converts it to SVG when you export it. The library just reads the numbers in order how they appear in the PSD file.

What the represent is: point with 2 control points attached to it
![image](https://user-images.githubusercontent.com/572298/120091173-f0df5780-c108-11eb-9149-be419d637ed6.png)

So it's x & y of 1st control point, then x & y of the actual point and then x & y 2nd control point (in SVG you encode curves instead of points)

**Comment by ryanlin1986** [comment]
Thanks, following code generate correct svg path:

`for (let i = 0; i < node.vectorMask.paths.length; i++) {
            let path = node.vectorMask.paths[i];
            let points = [];
            let pathPoints:string;
            for (let z = 0; z < path.knots.length; z++) {
                let knot = path.knots[z];
                points.push([knot.points[0] - offsetLeft, knot.points[1] - offsetTop]);
                points.push([knot.points[2] - offsetLeft, knot.points[3] - offsetTop]);
                points.push([knot.points[4] - offsetLeft, knot.points[5] - offsetTop]);
            }
            points.push(points[0]);
            points.push(points[1]);
            points.splice(0, 2);

            pathPoints = "M" + points[0].join(",");

            for (let j = 0; j < points.length; j += 3) {

                pathPoints += "C" + points[j].join(",");
                pathPoints += " " + points[j + 1].join(",");
                pathPoints += " " + points[j + 2].join(",");
            }

            if (!path.open) {
                pathPoints += " Z";
            }
        }`

**Comment by ryanlin1986** [comment]
Thanks for the explaination, really helpful.

**Comment by saberjsd** [comment]
So, How can I convert this `knots` points to the `canvas` shape, like `ctx.Rect()`, or `path` to svg?
Thanks for help me!

**Comment by saberjsd** [comment]
@Agamnentzar Thank you for help me. When I have some result at the next job, I will reply you.

**Comment by Agamnentzar** [comment]
@zwfun The PSD document doesn't contain SVG. Or are you asking how to generate SVG path from the PSD path? Or do you just want to know how to draw it on canvas?

**Comment by zwfun** [comment]
> 
i want to ask  how to generate SVG path from the PSD path。
How can I convert this knots points to the svg path.

Thank you so much。

**Comment by Agamnentzar** [comment]
> @saberjsd
> 
> The basic idea is that photoshop has: `control-point -> point -> control-point` and canvas has `control-point -> control-point -> point` So you use `context.bezierCurveTo(cp1x, cp1y, cp2x, cp2y, x, y)` and using one control point from previous point on one from current point, you also have to watch for points that have control-point at the same location as the point, those wouldn't need bezier curve, but simple line between the points.

Basically how I explained here, but just svg path `C` command with those points.

This will only work for simple paths though, in PSD shapes there can be paths with different blend modes, like combine, subtract, exclude. Those are not possible to easily translate to svg path as they require complex path operations.

**Comment by zwfun** [comment]
> @zwfun The PSD document doesn't contain SVG. Or are you asking how to generate SVG path from the PSD path? Or do you just want to know how to draw it on canvas?
![wecom-temp-126340-bd236e3ac4d85cd865cfd9f739b13265](https://user-images.githubusercontent.com/9522995/235038037-041b4399-184d-4879-9272-4a726cbc0e59.png)
what is the first point(pointX pointY)？<path d="M pointX pointY C x1 y1 ,  x2 y2, x y "/>

**Comment by Agamnentzar** [comment]
`M x, y C x2, y2, ...` and then at the end you do `C lastPoint_x2, lastPoint_y2, x1, y1, x, y Z`

**Comment by zwfun** [comment]
> `M x, y C x2, y2, ...` and then at the end you do `C lastPoint_x2, lastPoint_y2, x1, y1, x, y Z`

![wecom-temp-126340-bd236e3ac4d85cd865cfd9f739b13265](https://user-images.githubusercontent.com/9522995/235045376-f31e3a15-f517-4317-a7ec-2bd17c47731c.png)
I end up with wrong results, what is wrong please

**Comment by zwfun** [comment]
> `M x, y C x2, y2, ...` and then at the end you do `C lastPoint_x2, lastPoint_y2, x1, y1, x, y Z`

I end up with wrong results, what is wrong please
<img width="1094" alt="wecom-temp-624941-7e78a2d9140d0d0e8165b7107a7aa940" src="https://user-images.githubusercontent.com/9522995/235045552-25b94e07-498c-4c7b-b31b-558b6d151a77.png">

**Comment by Agamnentzar** [comment]
each `C` command has to be like this: `C ${knots[i].points[4]}, ${knots[i].points[5]} ${knots[i + 1].points[0]}, ${knots[i + 1].points[1]} ${knots[i + 1].points[2]}, ${knots[i + 1].points[3]}` so you take points from the current knot and next one

**Comment by zwfun** [comment]
> Thank you for help me. When I have some result at the next job, I will reply you.

Thanks for the explaination, really helpful.

**Comment by zhyyangyang** [comment]
> each `C` command has to be like this: `C ${knots[i].points[4]}, ${knots[i].points[5]} ${knots[i + 1].points[0]}, ${knots[i + 1].points[1]} ${knots[i + 1].points[2]}, ${knots[i + 1].points[3]}` so you take points from the current knot and next one

thank u  so much
