### ISSUE TITLE
Read psd throw an Exception

### ISSUE THREAD

**Issue by ryanlin1986** [Agamnentzar/ag-psd#71]
[test.zip](https://github.com/Agamnentzar/ag-psd/files/6623793/test.zip)

Here is the exception details:
![image](https://user-images.githubusercontent.com/11850439/121356562-8a0d3a00-c963-11eb-8a65-40d722ea3648.png)

**Comment by ryanlin1986** [comment]
Sorry, maybe this is a internal error, close

**Comment by Agamnentzar** [comment]
Fixed in version `14.0.1` it was missing handling for 2 new text anti-aliasing modes that were added recently to Photoshop.

**Comment by ryanlin1986** [comment]
Wow, that's really wonderful news, thanks for the quick fix.
