### ISSUE TITLE
Error when resizing an existing PSD

### ISSUE THREAD

**Issue by jeanpaze** [Agamnentzar/ag-psd#73]
Hey @Agamnentzar! I'm trying to resize an existing PSD but I'm getting this:

`Document canvas must have the same size as document`

I removed these 2 lines from `psdWriter.js`

```
if (imageData && (psd.width !== imageData.width || psd.height !== imageData.height))
    throw new Error('Document canvas must have the same size as document');
```

And it works as I wanted. Any idea for a permanent fix?

Cheers!

**Comment by Agamnentzar** [comment]
You have to also update psd.canvas to match document size, or just set it to `undefined` it if you don't need it (it's only needed for compatibility with very old versions of Photoshop)

**Comment by jeanpaze** [comment]
Perfect! `psd.canvas = undefined` did the trick. Thanks for that super-fast response!
