### ISSUE TITLE
The real z-index of layers

### ISSUE THREAD

**Issue by gofurnazarov** [Agamnentzar/ag-psd#74]
When I copy CSS of a layer using built-in Photoshop "Copy CSS" function, it give z-index of every layer. Example:

```
.slider {
  position: absolute;
  left: 0px;
  top: 0px;
  width: 1920px;
  height: 8945px;
  z-index: 688;
}
```
You can see at the end the layer has "688" z-index. So how can I get that "z-index" using ag-psd?

**Comment by Agamnentzar** [comment]
There's no concept of z-index in PSD file and you don't really need z-index if you're just drawing layers in order. I assume photoshop just assigns some consecutive numbers to the layers to ensure they're correctly ordered when it's generating this CSS code, you can just do the same or just don't set z-index.

**Comment by gofurnazarov** [comment]
Actually, my goal is to parse PSDs files and convert them to better HTML/CSS. That is why the z-index would so help to me cause there is no other way to know which layer is above or under another layer.

**Comment by Agamnentzar** [comment]
There's no z-index inside PSD files, so the layers are always in order, just like HTML elements. If you want to know if layer is behind another one, you just need to check if it comes before it on the layer tree.

**Comment by gofurnazarov** [comment]
Yeah, you are right. I think the issue is sloved.
