### ISSUE TITLE
Add handlers for 'iOpa' (fillOpacity) and 'tsly' (transparencyShapesLayer)

### ISSUE THREAD

**Issue by f2d** [Agamnentzar/ag-psd#78]
These fields are necessary to render some of my files, so I tried to add handlers myself.
It seems that both fields are 4-byte long with padding in 3 last bytes.
FillOpacity is 0-255 range and TransparencyShapesLayer is 1 or 0 toggle.

I have zero experience with js/ts build tools or any languages transpiled to JavaScript.
I did not know what to do with dist files I could build using the command from ag-psd readme - `gulp build`.
In the end, to see if it works, I took and patched a complete bundle from https://cdn.jsdelivr.net/npm/ag-psd@14.2.0/dist/bundle.js

Here is my patch, mimicking the existing code around it:
https://github.com/f2d/sprite_dress_up/commit/0b5d5c9b7a155a3c7bff616861188223d2b1427e

You may notice that I also added byte length output to "Unhandled additional info", because it was useful for adding handlers.

P.S.: forgot to attach some minimal 1x1px test files:
[test_FillOpacity_and_TransparencyShapesLayer_PSD_and_PSB.zip](https://github.com/Agamnentzar/ag-psd/files/7023799/test_FillOpacity_and_TransparencyShapesLayer_PSD_and_PSB.zip)

How it looks in SAI2:

![2021-08-20_18-58-24_003762_test_FillOpacity_and_TransparencyShapesLayer_SAI2_ver 2021 07 06 psb](https://user-images.githubusercontent.com/4068475/130285741-5271b11a-f886-4ef1-8ef5-1c95d68735f2.png)

What I get in JS with my patch:

![2021-08-20_18-59-22_003763_Developer Tools - fillOpacity present with transparencyShapesLayer = false](https://user-images.githubusercontent.com/4068475/130285800-3fdce35a-9b21-45d1-9f81-6c8c15ffbedc.png)

**Comment by Agamnentzar** [comment]
Fixed in 14.3.0 thank you for the test files and code
