### ISSUE TITLE
What are the points in the "knots?"

### ISSUE THREAD

**Issue by DOEHOONLEE** [Agamnentzar/ag-psd#80]
Hi, while I was trying to find the coordinates of warped image, I found points in `vectorMask.paths.knots`.

What do these points mean ??

![Screen Shot 2021-09-07 at 1 53 46 PM](https://user-images.githubusercontent.com/20305442/132286346-749b0485-e1bc-4f14-8db5-fef5c1850468.png)

**Comment by Agamnentzar** [comment]
A knot is a single point with 2 control points like this 
![image](https://user-images.githubusercontent.com/572298/132286491-f9a0c470-bda4-4c76-84ca-ea6498c16ed2.png)

**Comment by DOEHOONLEE** [comment]
oh, so 6 numbers within `points` array are the coordinates of 3 points??

**Comment by Agamnentzar** [comment]
Yes, those are X and Y coordinates of these 3 points

**Comment by DOEHOONLEE** [comment]
WOW! Thanks a lot!! :D
