### ISSUE TITLE
Question: Convert psd to tiff

### ISSUE THREAD

**Issue by konri** [Agamnentzar/ag-psd#85]
Is it possible to convert created psd file to tiff or some other image file?

**Comment by Agamnentzar** [comment]
This library is only for reading and writing PSD files, it does not generate images from generated data, you need to use Photoshop for that. Photoshop files saved from photoshop have embedded bitmap data for all layers as well as composite image data for the whole image, so if you have existing PSD files you might be able to get image data out of them and use your own tiff exporter to encode it.

**Comment by konri** [comment]
Thanks for replay I will do so.
