### ISSUE TITLE
Set active layer in photoshop on save 

### ISSUE THREAD

**Issue by konri** [Agamnentzar/ag-psd#86]
Hi, 
When I'm editing psd file in photoshop and select layer before save (ex. shadow layer), I can see that when I open photoshop on other computer, the same layer is active. Is a chance to select active layer with ag-psd? 

<img width="289" alt="Screenshot 2021-11-01 at 20 59 40" src="https://user-images.githubusercontent.com/3826473/139733872-ffb44b74-e549-4c15-8120-5b3ffd40a913.png">

I think the information about active layer is saved in psd file. 
Thanks for reply.

**Comment by Agamnentzar** [comment]
Can you send me PSD file that has this information saved ? it might be something added in recent version, I haven't seen it before

**Comment by konri** [comment]
https://drive.google.com/file/d/1RuFXrwPe-dy8mpXFt14k0l6qnanblRSK/view?usp=sharing

**Comment by Agamnentzar** [comment]
Sorry for the late response, I checked it and it seems it's already supported, I just missed it somehow.

You can get or set list of selected layers in `psd.imageResources.layerSelectionIds` which is an array of selected layer IDs

**Comment by konri** [comment]
Thank you so much, it works like a charm!
