### ISSUE TITLE
PSD doesn't show text change

### ISSUE THREAD

**Issue by stephanecoder** [Agamnentzar/ag-psd#88]
Hello,

I've made text changes to a PSD file and saved it but it doesn't show in Photoshop and export to png doesn't show the changes either. Any idea why?

Thanks in advance

**Comment by Agamnentzar** [comment]
You can read explanation here: https://github.com/Agamnentzar/ag-psd#updating-text-layers and see if that helps in your case

**Comment by stephanecoder** [comment]
Yes, I read it but it doesn't work. I'm still trying. Thanks

**Comment by Agamnentzar** [comment]
The problem is that Photoshop doesn't redraw text layers when you open the file, it expects text layer bitmap to be in the file, so you'd have to draw it yourself, this library doesn't update bitmaps for layers because it would require reimplementation of entire Photoshop rendering engine.

**Comment by stephanecoder** [comment]
I see. Thanks!

**Comment by RexYuan1114** [comment]
You have to update the canvas of text layer object.
