### ISSUE TITLE
node.js Error: Cavnas not initialized

### ISSUE THREAD

**Issue by MiGongOrg** [Agamnentzar/ag-psd#89]
```bash
Error: Cavnas not initialized, use initializeCanvas method to set up createCanvas method at Object.createCanvas
```

```javascript
import * as fs from 'fs';
import 'ag-psd/initialize-canvas'; // only needed for reading image data and thumbnails
import { readPsd } from 'ag-psd';
const buffer = fs.readFileSync('test.psd');
const psd = readPsd(buffer);
console.log('===>', psd);
```

**Comment by Agamnentzar** [comment]
try changing imports to require like this:
```
const fs = require('fs');
require('ag-psd/initialize-canvas'); // only needed for reading image data and thumbnails
const { readPsd } = require('ag-psd');
```

**Comment by MiGongOrg** [comment]
Is still an error

```
Cavnas not initialized, use initializeCanvas method to set up createCanvas method at Object.createCanvas
```

**Comment by Agamnentzar** [comment]
Hmm, are you using node or browser ? What version are you using ? Do you use any build tools with it ?

**Comment by MiGongOrg** [comment]
Q: node or browser ?
A: node

Q: What version are you using ?
A: node 14.15.0

Q: Do you use any build tools with it ?
A: "vue-electron": "^1.0.6", "electron-rebuild": "^3.2.5", "canvas": "^2.8.0"

Compile error: node canvas ("canvas": "^2.8.0")
Here is what worked for me: https://stackoverflow.com/a/52796884

But there was a problem: Cavnas not initialized, use initializeCanvas method to set up createCanvas method at Object.createCanvas

**Comment by Agamnentzar** [comment]
Not sure if node-canvas works correctly in electron, you can check if this code works:
```js
const { createCanvas, loadImage } = require('canvas')
const canvas = createCanvas(200, 200)
```

Is there a reason that you're reading PSD on the node process instead of browser process of node? If you want to display layers  in the window you will need browser process Canvas elements and not the node-canvas ones.

**Comment by MiGongOrg** [comment]
```
const { createCanvas, loadImage } = require('canvas');
const canvas = createCanvas(200, 200);

console.log(canvas);
```

Can work properly

![image](https://user-images.githubusercontent.com/10278269/143520504-a339dc8b-4322-403c-9fac-67ee1900b363.png)

Needs to be resolved in the node, Not in the browser

**Comment by Agamnentzar** [comment]
What if you replace ag-psd/initialize-canvas with this code:
```js
const { createCanvas, Image } = require('canvas');
const { initializeCanvas } = require('ag-psd');

function createCanvasFromData(data) {
	const image = new Image();
	image.src = Buffer.from(data);
	const canvas = createCanvas(image.width, image.height);
	canvas.getContext('2d').drawImage(image, 0, 0);
	return canvas;
}

initializeCanvas(createCanvas, createCanvasFromData);
```

**Comment by MiGongOrg** [comment]
WOW

A success! Thank you very much!

**Comment by Agamnentzar** [comment]
maybe something was assuming that `ag-psd/initialize-canvas` had no side-effects and was ignoring it, not sure why it didn't work

**Comment by MiGongOrg** [comment]
OK! thank you
