### ISSUE TITLE
How can I run this on local?

### ISSUE THREAD

**Issue by pradeepjain06** [Agamnentzar/ag-psd#92]
I am working on a demo project, where I need to merge 2 layer of PSD file. I find this on google. So now how can I run this project on local?

**Comment by Agamnentzar** [comment]
you can run it either in browser on using nodejs

**Comment by pradeepjain06** [comment]
as I found, after npm run build, it's generating bundle.js in dist folder and in test folder already index.html added with example code. so can I use this test folder to server on browser?

**Comment by Agamnentzar** [comment]
If you want to use library just follow the readme, install it into your own project using `npm install ag-psd` and then you can read PSD like this

```js
const fs = require('fs');
require('ag-psd/initialize-canvas');
const { readPsd } = require('ag-psd');

const buffer = fs.readFileSync('my-file.psd');

// read only document structure
const psd1 = readPsd(buffer, { skipLayerImageData: true, skipCompositeImageData: true, skipThumbnail: true });
console.log(psd1);

// read document structure and image data
const psd2 = readPsd(buffer);
console.log(psd2);
// by defaults `canvas` field type is HTMLCanvasElement, so it needs to be cast to `any`
// or node-canvas `Canvas` type, in order to call `toBuffer` method
fs.writeFileSync('layer-1.png', (psd2.children[0].canvas as any).toBuffer());
```

you can find more example code here https://github.com/Agamnentzar/ag-psd#nodejs
