### ISSUE TITLE
Is it possible to add a free transform parameter？

### ISSUE THREAD

**Issue by lanadeldel** [Agamnentzar/ag-psd#93]
![1](https://user-images.githubusercontent.com/48135307/153565819-a8920bbd-a70b-42dc-a6a1-605ddd800a11.jpeg)

**Comment by Agamnentzar** [comment]
Free transform is a transient modifier, meaning it's not saved after you execute it, it just changes the layer pixels. This library is only for reading and writing PSD files, it doesn't implement photoshop rendering engine for executing operations.

**Comment by lanadeldel** [comment]
1.I added a rect to the canvas：
<img width="573" alt="CCC60219-27DF-4CC8-98B3-B6340F03E45C" src="https://user-images.githubusercontent.com/48135307/153699770-4a2800bc-c548-4795-8e8f-7c3a77e48f1e.png">
2.This PSD file is not saved, but it can still be generated by the parser as an image:
<img width="275" alt="8A1ED3F6-3D82-45C9-9E4E-F734B6901074" src="https://user-images.githubusercontent.com/48135307/153699842-ab30f386-45e9-4d35-9c9e-eb4bf5b4a642.png">
3.When I clicked on the free transfom, the layer looked like this.:
<img width="126" alt="82459533-B5F7-4E91-A64E-EBF3E95B99BD" src="https://user-images.githubusercontent.com/48135307/153699908-e091ad99-31b4-42f6-8589-eb9181f10a98.png">
4:So I was wondering  could add a free transform parameter that would allow the parser to generate an image that I want, 
I don't need to save and update the file ， I can still get the transform image，and I'm sorry if that's a stupid idea:).

**Comment by lanadeldel** [comment]
1. i  added a red rect to the layer canvas :
<img width="573" alt="CCC60219-27DF-4CC8-98B3-B6340F03E45C" src="https://user-images.githubusercontent.com/48135307/153705791-25710b04-ce07-4bf3-9967-c32fdde8b710.png">,
2.This file has not been updated, but the PSD parser can still parse the changed canvas：
<img width="275" alt="8A1ED3F6-3D82-45C9-9E4E-F734B6901074" src="https://user-images.githubusercontent.com/48135307/153705848-a36119c5-c8a7-47be-a830-099a269ac527.png">
3.I clicked on the free transform and then the image(This image is replaced using ag-psd,) will be transform:
<img width="126" alt="82459533-B5F7-4E91-A64E-EBF3E95B99BD" src="https://user-images.githubusercontent.com/48135307/153706971-2e98b42e-15e6-433b-9447-33403277a67a.png">
4:So I thought If there is a free transform option，maybe I could use the parser tool to get the distorted images without updating the files? thank you very much

**Comment by Agamnentzar** [comment]
Oh ok, if you're talking about smart object layers then the transform is actually saved in the file, if you're not sure where something is in the file structure I recommend just printing entire object structure and see if you can find it in there.

The transform should be at `psdRead1.children[1].children[0].placedLayer.transform`, but photoshop will not show the change if you don't also apply the transform to the canvas. (It will show it correctly when you enter free transform mode in photoshop) This is because in case of smart objects the `canvas` field keeps pre-transformed version of the smart object that photoshop will use by default, and then it will go back to using actual linked image when you start editing it.

So to apply the transform properly you need to change `placedLayer.transform` field and then read smart object content, transform it and draw onto `canvas`

**Comment by lanadeldel** [comment]
> Oh ok, if you're talking about smart object layers then the transform is actually saved in the file, if you're not sure where something is in the file structure I recommend just printing entire object structure and see if you can find it in there.
> 
> The transform should be at `psdRead1.children[1].children[0].placedLayer.transform`, but photoshop will not show the change if you don't also apply the transform to the canvas. (It will show it correctly when you enter free transform mode in photoshop) This is because in case of smart objects the `canvas` field keeps pre-transformed version of the smart object that photoshop will use by default, and then it will go back to using actual linked image when you start editing it.
> 
> So to apply the transform properly you need to change `placedLayer.transform` field and then read smart object content, transform it and draw onto `canvas`
hiiii How can I convert the unit8array of smart layers on the web ?
I've used many methods to convert image paths to unit8array, and then the smart layer can't be opened.:(

**Comment by lanadeldel** [comment]
> Free transform is a transient modifier, meaning it's not saved after you execute it, it just changes the layer pixels. This library is only for reading and writing PSD files, it doesn't implement photoshop rendering engine for executing operations.
hiiiii How can I convert the unit8array of smart layers on the web ?
I've used many methods to convert image paths to unit8array, and then the smart layer can't be opened.:(

**Comment by Agamnentzar** [comment]
@lanadeldel something like this works for me
```js
const blob = new Blob([unit8array]);
const url = URL.createObjectURL(blob);
const img = new Image();
img.onload = () => {
  document.body.appendChild(img); // img is loaded here
  URL.revokeObjectURL(url);
};
img.onerror = () => {
  console.error('failed to load image');
};
img.src = url;
```
Be aware that the smart object can also be PSD file so you'd just use the readPsd again on it to read it.

**Comment by lanadeldel** [comment]
> ```js
> const blob = new Blob([unit8array]);
> const url = URL.createObjectURL(blob);
> const img = new Image();
> img.onload = () => {
>   document.body.appendChild(img); // img is loaded here
>   URL.revokeObjectURL(url);
> };
> img.onerror = () => {
>   console.error('failed to load image');
> };
> img.src = url;
> ```
thx is there something wrong with my unit8array? I get this error
`xhr.open('GET', '../src/assets/th2.png', true);
xhr.responseType = 'arraybuffer';
xhr.addEventListener('load', function (){
  const imgBuffer = xhr.response;
  console.log(new Uint8Array(imgBuffer))
   that.savePsd.linkedFiles[0] = {
  id: that.savePsd.linkedFiles[0].id,
  name: 'th2.png',
  data: new Uint8Array(imgBuffer),
};
const writepsd = writePsdBuffer(that.savePsd).buffer
that.$refs.framePage.contentWindow.postMessage(writepsd, "*");  
},false)`
`Alert: Unsupported format of the smart object (th2.png)`

**Comment by Agamnentzar** [comment]
Weird, it worked fine for me, do you mean that you get the alert from photoshop when trying to open the file? Maybe there's an issue with width and height of the image not matching the values in layer.placedLayer object ?

**Comment by lanadeldel** [comment]
> Weird, it worked fine for me, do you mean that you get the alert from photoshop when trying to open the file? Maybe there's an issue with width and height of the image not matching the values in layer.placedLayer object ?

Yes? I opened it in photopea ,haha :D,Thank you very much, I will check it
