### ISSUE TITLE
b.keyoriginshapebbox is undefined

### ISSUE THREAD

**Issue by lanadeldel** [Agamnentzar/ag-psd#94]
<img width="490" alt="6ACFD9D7-0CF1-4271-A474-E77A77D543BB" src="https://user-images.githubusercontent.com/48135307/156091892-c94e8138-1d02-4aaf-9e4d-14d73669154f.png">
hiii I used ag-psd to write the arraybuffer of the psd file, but some of the arraybuffer of the psd file causes this error.
This is the file where the error occurred：
"http://s3.cn-north-1.amazonaws.com.cn/photo-center-prov/images/91rr3AHARTasVhdqqVyNm4TGH9ub5wHb8VhZiE45/40bd6bffb940d8eefd8c5eee3eebb1ee.psd"

**Comment by Agamnentzar** [comment]
are you sure this file was created using ag-psd? It contains some sections that are not supported in ag-psd. Can you clarify what was the exact way you got the error?

**Comment by lanadeldel** [comment]
> are you sure this file was created using ag-psd? It contains some sections that are not supported in ag-psd. Can you clarify what was the exact way you got the error?

Why do you reply so fast every time lol,   I just use ag-psd to write arraybuffer...I also found that when the smart layer is on the second layer
<img width="648" alt="E0CD8A5D-005E-4F87-851E-2BCEB2404730" src="https://user-images.githubusercontent.com/48135307/156123075-cbd4abb2-0ad9-43e2-b552-3e15ab655efc.png">
：
There is no second layer of smart object here:
<img width="265" alt="F3570894-2ABA-415E-AEA6-D80748270396" src="https://user-images.githubusercontent.com/48135307/156123591-fbaddd53-7cae-43b3-97e5-8fa9ce6883ce.png">

**Comment by lanadeldel** [comment]
yesss,thank you:)
`const src = "http://s3.cn-north-1.amazonaws.com.cn/photo-center-prov/images/91rr3AHARTasVhdqqVyNm4TGH9ub5wHb8VhZiE45/40bd6bffb940d8eefd8c5eee3eebb1ee.psd"
xhr.open('GET',src, true);
xhr.responseType = 'arraybuffer';
xhr.addEventListener('load', function (){
  const buffer = xhr.response;
  const psdRead = readPsd(buffer);
  const writepsd = writePsdBuffer(psdRead).buffer
  that.$refs.framePage.contentWindow.postMessage(buffer, "*") // Using this constant is successful
  that.$refs.framePage.contentWindow.postMessage(writepsd, "*")  // An error will occur if this constant is used:Uncaught TypeError: J.keyOriginShapeBBox is undefined
},false)`

**Comment by Agamnentzar** [comment]
`writePsdBuffer` is intended for use in nodejs environment and generates nodejs `Buffer` object, in browsers you should use `writePsd` or `writePsdUint8Array` depending on of you need `ArrayBuffer` or `Uint8Array` object.

**Comment by Agamnentzar** [comment]
I managed to find the issue, published version `14.3.6` with a fix

**Comment by lanadeldel** [comment]
> http://s3.cn-north-1.amazonaws.com.cn/photo-center-prov/images/91rr3AHARTasVhdqqVyNm4TGH9ub5wHb8VhZiE45/40bd6bffb940d8eefd8c5eee3eebb1ee.psd

thank you very much!!!!
