### ISSUE TITLE
Is it possible to support gradient masks for layers

### ISSUE THREAD

**Issue by Briscer** [Agamnentzar/ag-psd#95]
First of all, thank you for your library，It's very useful.
Now I want to make an analysis of the layer gradient mask.and I searched the relevant issues，You said the gradient mask seems to have been generated as a separate bitmap. is it possible to get the information about the bitmap，for example, adding information to the canvas of the mask? 
thank you again!f

**Comment by Agamnentzar** [comment]
you should be able to get layer mask bitmap in `layer.mask.canvas` or `layer.mask.imageData` see https://github.com/Agamnentzar/ag-psd/blob/master/src/psd.ts#L223 for full structure of mask data

**Comment by Briscer** [comment]
ok  I see it.  it's my mistake. have a nice day!
